; ======================================================
; Gopher browser for Sprinter (DSS, 80x32 text)
; A port of nihirash's Moon Rabbit / Internet NEXTplorer (Z80) + agon-snail ideas.
;
; PHASE 3 - gopher engine (end-to-end browsing).
;   * Paged document buffer (src/doc.asm): fetched bytes live in a chain of
;     GetMem 16 KB pages, time-sharing WIN3 with the ISA window (CLAUDE.md §4a).
;     No 16 KB document limit; cap 16 pages (256 KB), then truncated.
;   * Gopher menus/text are parsed row-by-row (type/display/selector/host/port)
;     and rendered through the 30-row viewport directly from the doc pages.
;   * Enter follows a link (NET connect/send/recv into a fresh document);
;     Backspace goes back (history of navigation records, re-fetched on return);
;     Up/Down move, Left/Right page, Esc quits.
;   * Built-in "home" menu (WELCOME_DOC) is loaded at startup with no network,
;     so the browser is usable before the first fetch.
;   * Network errors are classified and shown on the status bar (no program
;     exit, no blocking "press a key"); NET.INIT runs once and is reused.
;
;   The WIN1 image holds all code + small state + stack (top 0x8000, down). A
;   GetMem page is mapped at WIN2 (0x8000) for the larger scratch buffers
;   (STAGE/LINE_BUF/REQ_BUF/HIST_DATA, see console.inc). Document pages and the
;   ISA window take turns in WIN3; we never SetWin2 over code because no code
;   lives in WIN2 (the proven wget layout).
; ======================================================

EXE_VERSION		EQU 1
LOAD_ADDR		EQU 0x4100
STACK_TOP		EQU 0x8000				; BOOT stack (WIN1): used only for early startup,
										; before the WIN2 page is mapped. The runtime stack is
										; RUN_STACK_TOP in the WIN2 page (START switches SP to
										; it once INIT_RUNTIME_PAGE has mapped the page).

DEFAULT_TIMEOUT	EQU 2000				; ms; also used by wcommon
RECV_TIMEOUT	EQU 5000				; ms per receive block

	DEVICE NOSLOT64K

	INCLUDE "macro.inc"
	INCLUDE "dss.inc"
	INCLUDE "sprinter.inc"
	INCLUDE "console.inc"
	INCLUDE "app_version.inc"			; APP_VERSION (our own; the kit has a version.inc too)
	INCLUDE "buildinfo.inc"				; BUILD_DATETIME (generated by the Makefile)

	MODULE MAIN

; --- viewport layout ---
HEADER_ROW		EQU 0
VIEW_TOP		EQU 1
VIEW_ROWS		EQU 30
STATUS_ROW		EQU 31

; --- history --- each level caches the whole document (page chain) so Back is
; instant (no re-fetch). Cap 8 levels; the oldest is freed on overflow.
HIST_MAX		EQU 8
; history record field offsets (see HIST_DATA in console.inc)
HR_KIND			EQU 0					; 1: 0=home, 1=network
HR_HOST			EQU 1					; 64
HR_PORT			EQU 65					; 8
HR_SEL			EQU 73					; 200
HR_TYPE			EQU 273					; 1
HR_SELIDX		EQU 274					; 2
HR_TOPIDX		EQU 276					; 2
HR_TITLE		EQU 278					; 64 (page title shown in the header)
HR_DOCSTATE		EQU 342					; 40 (DOC.SAVE_STATE: page chain + metadata)
HR_SIZE			EQU 382
TITLE_MAX		EQU 64

	ORG LOAD_ADDR - 0x0200
EXE_HEADER
	DB "EXE"
	DB EXE_VERSION
	DW 0x0200						; +0x04 (dword) header size = 512
	DW 0
	; +0x08 (word) LOADER size: make this a *loader EXE* by declaring our whole
	; code image as the loader. DSS then loads exactly this many body bytes and
	; leaves the EXE file OPEN (FM at (IX-3), file position right after the image),
	; so we can read the home page appended past the image (see LOAD_HOME_FILE).
	DW IMAGE_END - LOAD_ADDR
	DW 0
	DW 0
	DW 0
	DW START						; +0x10 load address
	DW START						; +0x12 entry point
	DW STACK_TOP					; +0x14 stack
	DS 490, 0

	ORG LOAD_ADDR

START
	LD		A, (IX-3)					; EXE file handle - DSS leaves a loader EXE open,
	LD		(home_fm), A				; FM at (IX-3); used to read the appended home page
	CALL	WCOMMON.INIT_VMODE			; record current mode so EXIT restores cleanly
	CALL	SHOW_BANNER					; version + build-date banner on load
	CALL	INIT_RUNTIME_PAGE			; map a fresh WIN2 page for the scratch buffers
	JP		C, MEM_ERROR
	; The WIN2 page is now ours, so move the stack into its top 4 KB
	; (RUN_STACK_TOP), away from the network lib's BSS under 0x8000. The early
	; boot frames on the WIN1 stack are done with (START exits via DSS, never
	; RETs through them), so abandoning them is safe.
	LD		SP, RUN_STACK_TOP
	CALL	INIT_PATHS					; resolve the EXE dir for DOWNLOAD\ (AppInfo #47)
	LD		HL, CLOCK_TICK_CB			; tick the clock during the kit's blocking waits
	LD		(WCOMMON.IDLE_CB), HL		; (INIT/connect/receive). The wrapper preserves IX/IY
										; (the kit restores only AF/BC/DE/HL around IDLE_CB).
										; Stack safety is now handled by RUN_STACK_TOP in WIN2.
	CALL	CFG.LOAD					; read GOPHER.CFG (viewers + settings); ignore if absent
	CALL	DOC.RESET
	CALL	TERM.CLS
	CALL	LOAD_HOME				; sets DOC_TITLE before the header is drawn
	CALL	DRAW_HEADER
	LD		HL, 0
	LD		(sel_index), HL
	LD		(top_index), HL
	CALL	RENDER_VIEWPORT
	CALL	SHOW_DOC_STATUS			; key help, or a "run NETUP" warning if no link

MAINLOOP
	CALL	CLOCK_TICK				; refresh HH:MM:SS in the header (only on change)
	CALL	IDLE_TICK				; after 3 s idle on a link, preview its target
	CALL	KBD.SCAN
	JR		Z, MAINLOOP
	CALL	RESET_IDLE				; a key -> restart the idle timer / clear preview

	CP		KEY_ESC
	JP		Z, CONFIRM_QUIT
	CP		KEY_ENTER
	JP		Z, ON_ENTER
	CP		KEY_BS
	JP		Z, ON_BACK

	; Ctrl combos. B = shift-state mask (bit 5 = Ctrl). For a Ctrl+letter the DSS
	; driver emits NO symbolic code (A/E = 0), so the letter is identified by its
	; physical keycode in D (masked with 0x7F, as the texteditor does for its own
	; Ctrl shortcuts). Only checked when a Ctrl key is down, so plain typing and
	; the arrow keys (handled below) are unaffected.
	LD		A, B
	AND		KB_CTRL | KB_L_CTRL | KB_R_CTRL
	JR		Z, .navkeys
	LD		A, D
	AND		0x7F
	CP		KEY_B					; Ctrl+B -> open the bookmarks file
	JP		Z, ON_BOOKMARKS
	CP		KEY_D					; Ctrl+D -> add the current page to bookmarks
	JP		Z, ON_ADD_BOOKMARK
.navkeys
	LD		A, D
	CP		KEY_UP
	JP		Z, ON_UP
	CP		KEY_DOWN
	JP		Z, ON_DOWN
	CP		KEY_LEFT
	JP		Z, ON_PGUP
	CP		KEY_RIGHT
	JP		Z, ON_PGDN
	CP		KEY_PGUP
	JP		Z, ON_PGUP
	CP		KEY_PGDN
	JP		Z, ON_PGDN
	CP		KEY_HOME
	JP		Z, ON_HOME
	CP		KEY_END
	JP		Z, ON_END
	CP		KEY_F10
	JP		Z, CONFIRM_QUIT			; F10 = quit (like Esc)
	JR		MAINLOOP

; ------------------------------------------------------
; Idle link preview: when the cursor rests on a link for ~3 s, show the link's
; target on the status bar. Driven by the per-second clock (now_sec, set by
; CLOCK_TICK), so no extra SYSTIME call. RESET_IDLE restarts the timer (and
; restores the status) on any keypress.
; ------------------------------------------------------
IDLE_TICK
	LD		A, (now_sec)
	LD		HL, idle_sec
	CP		(HL)
	RET		Z						; same second -> nothing
	LD		(HL), A					; advance the per-second counter
	LD		A, (preview_shown)
	OR		A
	RET		NZ						; preview already up -> leave it
	LD		A, (idle_count)
	CP		3
	RET		NC						; already counted (e.g. resting on a non-link)
	INC		A
	LD		(idle_count), A
	CP		3
	RET		NZ
	JP		SHOW_LINK_PREVIEW		; 3 s elapsed -> show the link under the cursor

; Restart the idle timer on activity; if a preview is up, restore the status.
; Preserves the KBD.SCAN result (AF/BC/DE) for the caller's key dispatch.
RESET_IDLE
	PUSH	AF
	PUSH	BC
	PUSH	DE
	XOR		A
	LD		(idle_count), A
	LD		A, (now_sec)
	LD		(idle_sec), A
	LD		A, (preview_shown)
	OR		A
	JR		Z, .done
	XOR		A
	LD		(preview_shown), A
	CALL	SHOW_DOC_STATUS			; restore the normal status line
.done
	POP		DE
	POP		BC
	POP		AF
	RET

; Esc at the menu asks for confirmation (so a stray Esc doesn't drop the user out
; of the browser). Y/y quits; any other key returns to browsing. The Esc that
; opened this is debounced (INP_WAIT_RELEASE).
CONFIRM_QUIT
	LD		HL, MSG_CONFIRM_QUIT
	CALL	SET_STATUS
	CALL	INP_WAIT_RELEASE
.poll
	CALL	CLOCK_TICK				; keep the clock live while the prompt is up
	CALL	KBD.SCAN
	JR		Z, .poll
	CP		'Y'
	JR		Z, QUIT
	CP		'y'
	JR		Z, QUIT
	CALL	INP_WAIT_RELEASE
	CALL	SHOW_DOC_STATUS			; restore the normal status line
	JP		MAINLOOP

QUIT
	LD		A, (net_inited)			; if we ever brought the ESP up, hand it back
	OR		A						; in command mode (socket closed) for the next program
	JR		Z, .noesp
	CALL	NET.SHUTDOWN
.noesp
	CALL	TERM.CLS				; leave a clean screen for the next program
	LD		D, 0
	LD		E, 0
	CALL	TERM.LOCATE
	CALL	SHOW_BANNER				; version + build-date banner on exit
	LD		B, 0
	JP		WCOMMON.EXIT

; Print the program banner (version + build date) at the cursor.
SHOW_BANNER
	LD		HL, MSG_BANNER
	JP		TERM.PUTS

MEM_ERROR
	PRINTLN	MSG_MEM_ERR
	LD		B, 3
	JP		WCOMMON.EXIT

; Allocate one 16 KB page and map it into WIN2 (0x8000) for the scratch buffers
; and the runtime stack. No need to remember the handle for after Dss.Exec: DSS
; saves/restores the parent's window registers across a child, and this page is a
; GetMem block tagged to our task (the child can't allocate over it), so WIN2 is
; ours again automatically on return.
INIT_RUNTIME_PAGE
	LD		B, 1
	LD		C, DSS_GETMEM
	RST		DSS
	RET		C
	LD		B, 0
	LD		C, DSS_SETWIN2			; A = handle from GetMem
	RST		DSS
	RET

; Re-enter the EXE directory (cwd may have changed, e.g. a launched child CHDIR'd),
; so relative paths (GOPHER.CFG, DOWNLOAD\) keep resolving next to the EXE.
CHDIR_EXE
	LD		A, (EXE_DIR)
	OR		A
	RET		Z						; EXE dir unknown (AppInfo failed) -> leave cwd
	LD		HL, EXE_DIR
	LD		C, DSS_CHDIR
	RST		DSS
	RET

; Change the working directory to the one containing GOPHER.EXE: DSS AppInfo #47
; B=1 returns the EXE's home directory (HL = buffer; path incl. trailing '\'),
; then CHDIR into it. So relative paths like DOWNLOAD\ resolve next to the EXE
; rather than in the launch cwd. (Idiom from package-hub's ChdirExeHome.) The
; buffer MUST be passed in HL (the API does EX DE,HL internally). Best-effort:
; if AppInfo or CHDIR is unavailable (older DSS) we stay in the current dir.
INIT_PATHS
	LD		HL, EXE_DIR
	LD		B, APPINFO_DIR			; B=1: directory containing the EXE
	LD		C, DSS_APPINFO
	RST		DSS						; HL-buffer -> "<drive>:<path>\" ASCIIZ
	RET		C						; not available -> leave cwd unchanged
	LD		HL, EXE_DIR
	LD		C, DSS_CHDIR
	RST		DSS
	RET

; ------------------------------------------------------
; Navigation. An in-page Up/Down recolours only the two changed rows in place
; (cheap, no repaint). An Up/Down at a viewport edge hardware-scrolls one line via
; BIOS Lp_Scroll_Up #8A + DI (SCROLL_VIEW), then draws the one newly exposed row.
; PgUp/PgDn full-redraw via RENDER_VIEWPORT (cheap now SEEK_LINE is O(1)) and are
; blocked when the selection can't move (at top/end).
; ------------------------------------------------------
ON_UP
	LD		HL, (sel_index)
	LD		A, H
	OR		L
	JP		Z, MAINLOOP				; already at the top
	DEC		HL
	LD		(new_sel), HL			; new_sel = sel-1
	LD		DE, (top_index)
	OR		A
	SBC		HL, DE					; new_sel - top; CF=1 if new_sel < top
	JR		C, .scroll
	; still on screen: recolour old + new row only (cheap, no scroll)
	CALL	DEHILITE_OLD
	LD		HL, (new_sel)
	LD		(sel_index), HL
	CALL	HILITE_NEW
	JP		MAINLOOP
.scroll
	; cursor was on the top row: hardware-scroll the viewport down one line and
	; draw the newly exposed top row.
	CALL	DEHILITE_OLD
	LD		HL, (top_index)
	DEC		HL
	LD		(top_index), HL
	LD		HL, (new_sel)
	LD		(sel_index), HL
	LD		B, 2					; BIOS Lp_Scroll_Up: 2 = down
	CALL	SCROLL_VIEW
	LD		A, 0					; new selected row appears at slot 0
	CALL	DRAW_NEW_SEL_ROW
	JP		MAINLOOP

ON_DOWN
	LD		HL, (sel_index)
	INC		HL
	LD		DE, (DOC.doc_lines)
	PUSH	HL
	OR		A
	SBC		HL, DE					; (sel+1) - lines; CF=1 if still in range
	POP		HL
	JP		NC, MAINLOOP			; already at the last line
	LD		(new_sel), HL			; new_sel = sel+1
	; visible if new_sel < top + VIEW_ROWS
	LD		HL, (top_index)
	LD		DE, VIEW_ROWS
	ADD		HL, DE
	EX		DE, HL					; DE = top + VIEW_ROWS
	LD		HL, (new_sel)
	OR		A
	SBC		HL, DE					; new_sel - bottom; CF=1 if visible
	JR		C, .inpage
	; cursor ran off the bottom: hardware-scroll up one line, draw new bottom row
	CALL	DEHILITE_OLD
	LD		HL, (top_index)
	INC		HL
	LD		(top_index), HL
	LD		HL, (new_sel)
	LD		(sel_index), HL
	LD		B, 1					; BIOS Lp_Scroll_Up: 1 = up
	CALL	SCROLL_VIEW
	LD		A, VIEW_ROWS - 1		; new selected row appears at the bottom slot
	CALL	DRAW_NEW_SEL_ROW
	JP		MAINLOOP
.inpage
	CALL	DEHILITE_OLD
	LD		HL, (new_sel)
	LD		(sel_index), HL
	CALL	HILITE_NEW
	JP		MAINLOOP

; ---- incremental-render helpers ----
; De-highlight the row at the current sel_index (recolour to its natural attr,
; known from sel_type), leaving its text untouched.
DEHILITE_OLD
	LD		A, (sel_type)
	CALL	ATTR_FOR_TYPE
	PUSH	AF
	LD		HL, (sel_index)
	POP		AF
	JP		RECOLOR_ROW

; Highlight the row at the (just updated) sel_index, caching its gopher type.
HILITE_NEW
	LD		BC, (sel_index)
	CALL	GET_ROW_TYPE
	LD		(sel_type), A
	LD		HL, (sel_index)
	LD		A, ATTR_HILITE
	JP		RECOLOR_ROW

; Set the attribute of all SCR_W cells of the row showing line HL (no text
; rewrite). A = attribute. Uses BIOS Set_Place + Print_Atr (WIN2-resident stack).
RECOLOR_ROW
	PUSH	AF
	LD		DE, (top_index)
	OR		A
	SBC		HL, DE					; HL = slot (line - top)
	LD		A, L
	ADD		VIEW_TOP
	LD		D, A					; D = screen row
	LD		E, 0					; E = col
	LD		C, BIOS_SET_PLACE
	DI
	RST		BIOS
	POP		AF
	LD		E, A					; E = attribute
	LD		B, SCR_W
	LD		C, BIOS_PRINT_ATR
	RST		BIOS
	EI
	RET

; Hardware-scroll the 30-row viewport by one line. B = 1 (up) / 2 (down). Uses
; BIOS Lp_Scroll_Up (#8A): B=dir, D=begin-line, E=line-count (per BIOS docs and
; texteditor/SpecTalkZX). Interrupts OFF around it (the routine remaps VRAM and
; must not be interrupted) - this is what hung the DSS Scroll #55 path.
SCROLL_VIEW
	LD		D, VIEW_TOP				; begin line (0-based first viewport row)
	LD		E, VIEW_ROWS			; number of lines
	LD		C, BIOS_SCROLL			; #8A
	PUSH	IX
	DI
	RST		BIOS
	EI
	POP		IX
	RET

; Draw the selected row in full at slot A (a freshly scrolled-in row), highlighted,
; and cache its gopher type for the next de-highlight.
DRAW_NEW_SEL_ROW
	LD		(r_slot), A
	LD		A, 1
	LD		(r_sel_flag), A
	LD		BC, (sel_index)
	CALL	DRAW_ROW_LINE
	LD		A, (row_type)
	LD		(sel_type), A
	RET

; Draw the full row for line BC at slot r_slot with flag r_sel_flag.
DRAW_ROW_LINE
	CALL	DOC.SEEK_LINE
	CALL	DOC.AT_END
	JP		C, BLANK_ROW
	CALL	DOC.NEXT_LINE
	CALL	PARSE_ROW
	JP		DRAW_ROW

; A = natural (non-selected) attribute for gopher type A (in a menu). In a text
; document every line is normal.
ATTR_FOR_TYPE
	PUSH	AF
	LD		A, (DOC_TYPE_CUR)
	CP		'1'
	JR		Z, .menu
	POP		AF
	LD		A, ATTR_NORM
	RET
.menu
	POP		AF
	CP		'i'
	JR		Z, .norm
	CP		'.'
	JR		Z, .norm
	LD		A, ATTR_LINK
	RET
.norm
	LD		A, ATTR_NORM
	RET

; BC = line index -> A = gopher type byte ('i' if past the end of the document).
GET_ROW_TYPE
	CALL	DOC.SEEK_LINE
	CALL	DOC.AT_END
	LD		A, 'i'
	RET		C
	JP		DOC.RD_BYTE

; Page down: move the viewport top down by one page (clamped so the last page is
; full), keeping the cursor at the same screen slot.
ON_PGDN
	LD		HL, (DOC.doc_lines)
	LD		A, H
	OR		L
	JP		Z, MAINLOOP				; empty doc
	LD		HL, (top_index)
	LD		DE, VIEW_ROWS
	ADD		HL, DE					; top + VIEW_ROWS
	LD		(pg_tmp), HL
	CALL	MAX_TOP					; HL = max top (lines - VIEW_ROWS, >= 0)
	LD		DE, (pg_tmp)
	PUSH	HL
	OR		A
	SBC		HL, DE					; max_top - (top+page); CF=1 if max_top < that
	POP		HL						; HL = max_top
	JR		C, .use					; clamp to max_top
	LD		HL, (pg_tmp)			; top+page is within range
.use
	JP		PAGE_NAV				; HL = new top

; Page up: move the viewport top up by one page (floor 0), same cursor slot.
ON_PGUP
	LD		HL, (DOC.doc_lines)
	LD		A, H
	OR		L
	JP		Z, MAINLOOP
	LD		HL, (top_index)
	LD		DE, VIEW_ROWS
	OR		A
	SBC		HL, DE					; top - VIEW_ROWS
	JR		NC, PAGE_NAV
	LD		HL, 0
	JP		PAGE_NAV

; HL = max(0, doc_lines - VIEW_ROWS).
MAX_TOP
	LD		HL, (DOC.doc_lines)
	LD		DE, VIEW_ROWS
	OR		A
	SBC		HL, DE
	RET		NC
	LD		HL, 0
	RET

; PAGE_NAV: HL = the desired new top_index. Keeps the cursor at its current slot
; (sel - top), clamps the new selection to lines-1, and renders. Does nothing if
; neither top nor selection actually changed (already at the boundary).
PAGE_NAV
	LD		(pg_ntop), HL
	; slot = sel - top
	LD		HL, (sel_index)
	LD		DE, (top_index)
	OR		A
	SBC		HL, DE					; HL = slot
	; new_sel = new_top + slot
	LD		DE, (pg_ntop)
	ADD		HL, DE
	; clamp to lines-1
	LD		DE, (DOC.doc_lines)
	DEC		DE
	PUSH	HL
	OR		A
	SBC		HL, DE					; new_sel - (lines-1); CF=1 if in range
	POP		HL
	JR		C, .sok
	EX		DE, HL					; clamp to lines-1
.sok
	LD		(pg_nsel), HL
	; block if nothing changed
	LD		HL, (pg_ntop)
	LD		DE, (top_index)
	OR		A
	SBC		HL, DE
	JR		NZ, .go
	LD		HL, (pg_nsel)
	LD		DE, (sel_index)
	OR		A
	SBC		HL, DE
	JP		Z, MAINLOOP
.go
	LD		HL, (pg_ntop)
	LD		(top_index), HL
	LD		HL, (pg_nsel)
	LD		(sel_index), HL
	JP		REDRAW
pg_tmp	DW 0
pg_ntop	DW 0
pg_nsel	DW 0

REDRAW
	CALL	RENDER_VIEWPORT
	JP		MAINLOOP

; Home: jump to the start of the document.
ON_HOME
	LD		HL, 0
	LD		(sel_index), HL
	LD		(top_index), HL
	JP		REDRAW

; End: jump to the last line (cursor on it, last page shown).
ON_END
	LD		HL, (DOC.doc_lines)
	LD		A, H
	OR		L
	JP		Z, MAINLOOP				; empty doc
	DEC		HL
	LD		(sel_index), HL			; sel = lines - 1
	CALL	MAX_TOP					; HL = max(0, lines - VIEW_ROWS)
	LD		(top_index), HL
	JP		REDRAW

; Header + full viewport repaint (after a page change).
REDRAW_FULL
	CALL	DRAW_HEADER
	JP		RENDER_VIEWPORT

; Clamp sel_index into [0, doc_lines-1]; zero the view if the doc is empty.
CLAMP_SEL
	LD		HL, (DOC.doc_lines)
	LD		A, H
	OR		L
	JR		NZ, .nz
	LD		HL, 0
	LD		(sel_index), HL
	LD		(top_index), HL
	RET
.nz
	DEC		HL						; lines-1
	LD		DE, (sel_index)
	PUSH	HL
	OR		A
	SBC		HL, DE					; (lines-1) - sel; CF=1 if sel > lines-1
	POP		HL
	RET		NC
	LD		(sel_index), HL
	RET

; ------------------------------------------------------
; Enter: open the link on the selected row.
; ------------------------------------------------------
ON_ENTER
	LD		A, (DOC_TYPE_CUR)
	CP		'1'
	JP		NZ, MAINLOOP			; text document has no links
	LD		BC, (sel_index)
	CALL	DOC.SEEK_LINE
	LD		HL, (sel_index)
	LD		DE, (DOC.doc_lines)
	OR		A
	SBC		HL, DE
	JP		NC, MAINLOOP			; selection past end
	CALL	DOC.NEXT_LINE
	CALL	PARSE_ROW
	LD		A, (row_type)
	CP		'1'
	JR		Z, .follow
	CP		'0'
	JR		Z, .follow
	CP		'7'
	JR		Z, .search
	LD		A, (row_type)
	CALL	IS_BIN_TYPE				; 9/5/g/I/s/;/d/p -> downloadable
	JP		Z, .download
	LD		A, (row_type)
	CP		'h'
	JP		Z, .urllink				; URL: link (gopher:// navigates; web link shown)
	CP		'i'
	JP		Z, MAINLOOP
	CP		'.'
	JP		Z, MAINLOOP
	JP		.unsupported			; other types - later phase
.follow
	LD		HL, (p_host)
	LD		A, (HL)
	OR		A
	JP		Z, .unsupported			; no host on this row
	; A link that points back at the previous page unwinds history (instant)
	; instead of re-fetching the parent and growing the history stack. Detect it
	; two ways: (a) the link's target equals the previous page (robust); (b) it
	; reads as a "Back"/".." item (catches parents reached by a different selector,
	; e.g. "Back to home page" -> "/").
	LD		A, (hist_sp)
	OR		A
	JR		Z, .follow_go			; no history -> nothing to go back to
	CALL	MATCHES_PREV_PAGE
	JP		NC, ON_BACK				; same host/port/selector as previous page
	CALL	IS_BACK_LINK
	JP		NC, ON_BACK				; back-titled link
.follow_go
	CALL	PUSH_HIST				; cache the page we are leaving (nav + its doc pages)
	CALL	DOC.NEW					; detach those pages; start a fresh empty doc
	CALL	COPY_NAV_FROM_ROW		; title/host/port/selector/type from the parsed row
	JP		GOTO_FETCH
.search
	; type 7: ask for a query, send "<selector> TAB <query>", show the menu result
	LD		HL, (p_host)
	LD		A, (HL)
	OR		A
	JP		Z, .unsupported			; no host on this row
	LD		HL, MSG_SEARCH
	LD		DE, SEARCH_BUF
	LD		B, SEARCH_MAX
	CALL	INPUT_LINE
	JR		C, .search_cancel		; Esc -> abort
	CALL	PUSH_HIST
	CALL	DOC.NEW
	LD		HL, (p_disp)			; title = the search item's text
	LD		DE, DOC_TITLE
	LD		B, TITLE_MAX
	CALL	STRCPYN
	LD		HL, (p_host)
	LD		DE, HOST_CUR
	LD		B, 64
	CALL	STRCPYN
	LD		HL, (p_port)
	LD		DE, PORT_CUR
	LD		B, 8
	CALL	STRCPYN
	; SEL_CUR = <original selector> TAB <query>
	LD		HL, (p_sel)
	LD		DE, SEL_CUR
	CALL	COPYZ					; copy selector (no NUL); DE -> end
	LD		A, 9
	LD		(DE), A					; TAB
	INC		DE
	LD		HL, SEARCH_BUF
	CALL	COPYZ					; append query; DE -> end
	XOR		A
	LD		(DE), A					; NUL-terminate
	LD		A, '1'					; search results are a gopher menu
	LD		(DOC_TYPE_CUR), A
	LD		A, 1
	LD		(cur_kind), A
	JP		GOTO_FETCH
.search_cancel
	LD		HL, MSG_STATUS			; restore the help line over the prompt
	CALL	SET_STATUS
	JP		MAINLOOP
.unsupported
	LD		HL, MSG_UNSUPPORTED
	CALL	SET_STATUS
	JP		MAINLOOP
.download
	; binary/media item: stream it to download\<name>, leaving the current
	; document (and history) untouched. Uses dedicated DL_* buffers so HOST_CUR/
	; SEL_CUR (the live page's nav) are not disturbed.
	LD		HL, (p_host)
	LD		A, (HL)
	OR		A
	JP		Z, .unsupported			; no host on this row
	LD		HL, (p_host)
	LD		DE, DL_HOST
	LD		B, 64
	CALL	STRCPYN
	LD		HL, (p_port)
	LD		DE, DL_PORT
	LD		B, 8
	CALL	STRCPYN
	LD		HL, (p_sel)
	LD		DE, DL_SEL
	LD		B, 200
	CALL	STRCPYN
	CALL	MAKE_DLNAME				; DL_SEL -> DL_NAME (8.3) and DL_PATH
	CALL	DOWNLOAD				; CF=1 on error (last_err set)
	JR		C, .dlfail
	CALL	SHOW_SAVED
	CALL	MAYBE_OPEN_DOWNLOAD		; offer/launch a viewer per GOPHER.CFG
	JP		MAINLOOP
.dlfail
	CALL	SHOW_ERROR
	JP		MAINLOOP
.urllink
	; gopher type 'h': the selector is a URL, usually "URL:<url>". gopher:// is
	; navigated like a normal link; other schemes (http/ftp/mailto/...) are routed
	; to a program from [urls] in GOPHER.CFG (scheme=program %url%), after a confirm.
	LD		HL, (p_sel)
	CALL	STRIP_URL_PREFIX		; HL -> URL ("URL:" stripped if present)
	LD		(url_full), HL
	LD		DE, SCHEME_GOPHER
	CALL	SKIP_PREFIX_CI			; gopher:// ?  CF=0 and HL past it if so
	JR		C, .h_other
	LD		(url_ptr), HL			; HL now points past "gopher://"
	CALL	PUSH_HIST				; cache the page we leave
	CALL	DOC.NEW
	LD		HL, (p_disp)			; title = the link text
	LD		DE, DOC_TITLE
	LD		B, TITLE_MAX
	CALL	STRCPYN
	LD		HL, (url_ptr)
	CALL	PARSE_GOPHER_URL		; -> HOST_CUR / PORT_CUR / SEL_CUR / DOC_TYPE_CUR
	LD		A, 1
	LD		(cur_kind), A
	JP		GOTO_FETCH
.h_other
	LD		HL, (url_full)			; scheme (up to ':') -> URL_SCHEME
	CALL	GET_URL_SCHEME
	LD		HL, URL_SCHEME			; a program for this scheme in [urls]?
	CALL	CFG.HANDLER_FOR_SCHEME	; DE = command template, CF=1 if none
	JR		C, .h_nohandler
	LD		(open_tpl), DE
	CALL	SHOW_URL_HEADER			; show the URL (header) so it stays during the ask
	CALL	SKIP_ASK				; CF=1 -> launch without asking
	JR		C, .h_exec
	CALL	CONFIRM_OPEN			; CF=1 -> user declined
	JR		C, .h_cancel
.h_exec
	LD		HL, (open_tpl)
	LD		DE, (url_full)
	CALL	CFG.BUILD_CMD			; expand %url% -> CMD_BUF
	CALL	EXEC_PROGRAM
	PUSH	AF						; CF = launch error
	CALL	REDRAW_FULL				; the program/header took over - repaint
	POP		AF
	JR		C, .h_execfail
	CALL	SHOW_DOC_STATUS
	JP		MAINLOOP
.h_execfail
	LD		HL, MSG_EXEC_FAIL
	CALL	SET_STATUS				; CALL (not JP): ON_ENTER is a JP target from
	JP		MAINLOOP				; MAINLOOP, so end with JP, not a bare RET
.h_cancel
	CALL	REDRAW_FULL				; restore the header (URL was shown there)
	CALL	SHOW_DOC_STATUS
	JP		MAINLOOP
.h_nohandler
	LD		HL, (url_full)			; no [urls] entry -> just show the URL
	CALL	SHOW_WEBLINK
	JP		MAINLOOP

; Copy the parsed row's link fields into the current nav (used by .follow).
COPY_NAV_FROM_ROW
	LD		HL, (p_disp)
	LD		DE, DOC_TITLE
	LD		B, TITLE_MAX
	CALL	STRCPYN
	LD		HL, (p_host)
	LD		DE, HOST_CUR
	LD		B, 64
	CALL	STRCPYN
	LD		HL, (p_port)
	LD		DE, PORT_CUR
	LD		B, 8
	CALL	STRCPYN
	LD		HL, (p_sel)
	LD		DE, SEL_CUR
	LD		B, 200
	CALL	STRCPYN
	LD		A, (row_type)
	LD		(DOC_TYPE_CUR), A
	LD		A, 1
	LD		(cur_kind), A
	RET

; Fetch the current nav into the fresh (DOC.NEW'd) document and show it; on error
; drop the partial doc and restore the cached previous page. Assumes PUSH_HIST +
; DOC.NEW were already done and HOST_CUR/PORT_CUR/SEL_CUR/title/type/kind are set.
GOTO_FETCH
	CALL	DO_FETCH
	JR		C, .err
	LD		HL, 0
	LD		(sel_index), HL
	LD		(top_index), HL
	CALL	REDRAW_FULL
	CALL	SHOW_DOC_STATUS
	JP		MAINLOOP
.err
	CALL	DOC.RESET
	CALL	POP_HIST				; restores the previous doc's pages (no re-fetch)
	CALL	CLAMP_SEL
	CALL	REDRAW_FULL
	CALL	SHOW_ERROR
	JP		MAINLOOP

; ------------------------------------------------------
; Type-'h' URL helpers.
; ------------------------------------------------------
; HL = selector -> HL advanced past a leading "URL:" (case-insensitive) if present.
STRIP_URL_PREFIX
	LD		DE, PFX_URL
	CALL	SKIP_PREFIX_CI
	RET								; HL advanced (CF=0) or unchanged (CF=1); both ok

; If the ASCIIZ at HL starts with the ASCIIZ prefix at DE (case-insensitive),
; return CF=0 and HL advanced past the prefix; else CF=1 and HL unchanged.
SKIP_PREFIX_CI
	PUSH	HL
.l
	LD		A, (DE)
	OR		A
	JR		Z, .match				; prefix consumed -> match
	CP		'a'						; uppercase the prefix char
	JR		C, .pu
	CP		'z' + 1
	JR		NC, .pu
	SUB		0x20
.pu
	LD		B, A
	LD		A, (HL)					; uppercase the input char
	CP		'a'
	JR		C, .su
	CP		'z' + 1
	JR		NC, .su
	SUB		0x20
.su
	CP		B
	JR		NZ, .no
	INC		HL
	INC		DE
	JR		.l
.no
	POP		HL
	SCF
	RET
.match
	POP		AF						; drop the saved HL, keep the advanced one
	OR		A						; CF=0
	RET

; Decide whether the selected row is a "go to the previous page" link (e.g.
; gophermaps often carry a "Back to previous page" / ".." entry). Looks only at
; the display text (p_disp), case-insensitively: matches a leading ".." or the
; word "back" (with a word boundary, so "Background" is NOT treated as Back).
; Returns CF=0 if it's a back link, CF=1 otherwise. Clobbers A/HL/DE.
IS_BACK_LINK
	LD		HL, (p_disp)
	LD		DE, PHRASE_DOTDOT
	CALL	SKIP_PREFIX_CI			; leading ".."?
	RET		NC						; yes -> back link (CF=0)
	LD		HL, (p_disp)
	LD		DE, PHRASE_BACK
	CALL	SKIP_PREFIX_CI			; leading "back"? (HL advanced past it)
	RET		C						; no -> not a back link (CF=1)
	LD		A, (HL)					; char right after "back"
	OR		A
	RET		Z						; "back" exactly -> back link (CF=0)
	CP		'a'						; a letter after "back" (e.g. "Background")?
	JR		C, .boundary
	CP		'z' + 1
	JR		C, .notback
.boundary
	CP		'A'
	JR		C, .yes					; punctuation/space -> word boundary
	CP		'Z' + 1
	JR		NC, .yes
.notback
	SCF								; letter follows -> not a back link
	RET
.yes
	OR		A						; CF=0
	RET

PHRASE_DOTDOT		DB ".." , 0
PHRASE_BACK			DB "back", 0

; Decide whether the selected row links back at the page we came from, i.e. its
; target (p_host/p_port/p_sel, pointers into the parsed row) is byte-for-byte the
; previous history record (top of the stack). This is the robust back detection:
; following such a link should pop history, not push a new copy of the parent.
; Assumes the caller already checked hist_sp > 0. CF=0 if it matches the previous
; page, CF=1 otherwise. Clobbers A/BC/DE/HL.
MATCHES_PREV_PAGE
	LD		A, (hist_sp)
	DEC		A
	CALL	HREC_ADDR				; HL = previous record
	PUSH	HL
	LD		DE, HR_HOST
	ADD		HL, DE
	EX		DE, HL					; DE = &HR_HOST
	LD		HL, (p_host)
	CALL	STREQ
	POP		HL
	RET		C						; host differs
	PUSH	HL
	LD		DE, HR_PORT
	ADD		HL, DE
	EX		DE, HL
	LD		HL, (p_port)
	CALL	STREQ
	POP		HL
	RET		C						; port differs
	LD		DE, HR_SEL
	ADD		HL, DE
	EX		DE, HL
	LD		HL, (p_sel)
	JP		STREQ					; selector: CF from STREQ is the verdict

; Compare ASCIIZ strings at HL and DE. CF=0 if equal, CF=1 if not. Clobbers A;
; preserves HL/DE.
STREQ
	PUSH	HL
	PUSH	DE
.l
	LD		A, (DE)
	CP		(HL)
	JR		NZ, .ne
	OR		A
	JR		Z, .eq					; both reached NUL together -> equal
	INC		HL
	INC		DE
	JR		.l
.eq
	POP		DE
	POP		HL
	OR		A						; CF=0
	RET
.ne
	POP		DE
	POP		HL
	SCF
	RET

; Parse "host[:port][/<type><selector>]" at HL into HOST_CUR / PORT_CUR / SEL_CUR /
; DOC_TYPE_CUR (defaults: port 70, type '1', empty selector). Fields are length-
; capped to their buffers.
PARSE_GOPHER_URL
	LD		DE, HOST_CUR			; --- host (up to ':' '/' or end) ---
	LD		B, 63
.h
	LD		A, B
	OR		A
	JR		Z, .hd
	LD		A, (HL)
	OR		A
	JR		Z, .hd
	CP		':'
	JR		Z, .hd
	CP		'/'
	JR		Z, .hd
	LD		(DE), A
	INC		DE
	INC		HL
	DEC		B
	JR		.h
.hd
	XOR		A
	LD		(DE), A					; NUL-terminate host
	LD		A, (HL)					; --- optional :port ---
	CP		':'
	JR		NZ, .defport
	INC		HL
	LD		DE, PORT_CUR
	LD		B, 7
.p
	LD		A, B
	OR		A
	JR		Z, .pd
	LD		A, (HL)
	OR		A
	JR		Z, .pd
	CP		'/'
	JR		Z, .pd
	LD		(DE), A
	INC		DE
	INC		HL
	DEC		B
	JR		.p
.pd
	XOR		A
	LD		(DE), A
	JR		.path
.defport
	LD		A, '7'
	LD		(PORT_CUR), A
	LD		A, '0'
	LD		(PORT_CUR + 1), A
	XOR		A
	LD		(PORT_CUR + 2), A
.path
	LD		A, (HL)					; --- /<type><selector> ---
	CP		'/'
	JR		NZ, .nopath
	INC		HL						; skip '/'
	LD		A, (HL)
	OR		A
	JR		Z, .nopath				; "/" with nothing after -> defaults
	LD		(DOC_TYPE_CUR), A		; gopher type byte
	INC		HL
	LD		DE, SEL_CUR				; selector = the rest
	LD		B, 199
.s
	LD		A, B
	OR		A
	JR		Z, .sterm
	LD		A, (HL)
	LD		(DE), A
	OR		A
	RET		Z						; copied the NUL -> done
	INC		HL
	INC		DE
	DEC		B
	JR		.s
.sterm
	XOR		A
	LD		(DE), A
	RET
.nopath
	LD		A, '1'
	LD		(DOC_TYPE_CUR), A
	XOR		A
	LD		(SEL_CUR), A
	RET

; Show a (non-gopher) URL on the status line, capped to fit the row.
SHOW_WEBLINK
	PUSH	HL						; url
	LD		HL, MSG_LINKPFX
	LD		DE, WEBLINK_BUF
	CALL	COPYZ					; "Web link: " -> DE at end
	POP		HL						; url
.l
	LD		A, D					; stop near the end of the buffer
	CP		high (WEBLINK_BUF + 78)
	JR		C, .cp
	LD		A, E
	CP		low (WEBLINK_BUF + 78)
	JR		NC, .done
.cp
	LD		A, (HL)
	OR		A
	JR		Z, .done
	LD		(DE), A
	INC		DE
	INC		HL
	JR		.l
.done
	XOR		A
	LD		(DE), A
	LD		HL, WEBLINK_BUF
	JP		SET_STATUS

; Copy the URL scheme (up to the first ':') at HL into URL_SCHEME (e.g. "http").
GET_URL_SCHEME
	LD		DE, URL_SCHEME
	LD		B, 15
.l
	LD		A, B
	OR		A
	JR		Z, .done
	LD		A, (HL)
	OR		A
	JR		Z, .done
	CP		':'
	JR		Z, .done
	LD		(DE), A
	INC		DE
	INC		HL
	DEC		B
	JR		.l
.done
	XOR		A
	LD		(DE), A
	RET

; Show "Open URL: <url>" on the header row (so it stays visible while the confirm
; prompt is on the status row). url_full holds the URL; capped to fit before the clock.
SHOW_URL_HEADER
	LD		HL, MSG_OPENURL
	LD		DE, WEBLINK_BUF
	CALL	COPYZ					; "Open URL: " -> DE at end
	LD		HL, (url_full)
.l
	LD		A, D
	CP		high (WEBLINK_BUF + 68)
	JR		C, .cp
	LD		A, E
	CP		low (WEBLINK_BUF + 68)
	JR		NC, .done
.cp
	LD		A, (HL)
	OR		A
	JR		Z, .done
	LD		(DE), A
	INC		DE
	INC		HL
	JR		.l
.done
	XOR		A
	LD		(DE), A
	LD		D, HEADER_ROW			; paint the header and print it there
	LD		E, 0
	LD		H, 1
	LD		L, SCR_W
	LD		B, ATTR_HEADER
	LD		A, ' '
	CALL	TERM.FILL
	LD		D, HEADER_ROW
	LD		E, 1
	CALL	TERM.LOCATE
	LD		HL, WEBLINK_BUF
	CALL	TERM.PUTS
	LD		A, 0xFF					; let the clock repaint over its corner next tick
	LD		(clk_last), A
	RET

; Show the target of the link under the cursor on the status bar (idle preview).
; "gopher://host:port/<type><selector>" for normal links; the raw URL for type 'h'.
SHOW_LINK_PREVIEW
	LD		A, (DOC_TYPE_CUR)
	CP		'1'
	RET		NZ						; text document -> no links
	LD		HL, (DOC.doc_lines)
	LD		A, H
	OR		L
	RET		Z						; empty doc
	LD		HL, (sel_index)
	LD		DE, (DOC.doc_lines)
	OR		A
	SBC		HL, DE
	RET		NC						; selection past the end
	LD		BC, (sel_index)
	CALL	DOC.SEEK_LINE
	CALL	DOC.NEXT_LINE
	CALL	PARSE_ROW
	LD		A, (row_type)
	CP		'i'
	RET		Z						; info / non-link rows -> nothing
	CP		'.'
	RET		Z
	LD		HL, (p_host)
	LD		A, (HL)
	OR		A
	RET		Z						; no host on this row
	LD		A, (row_type)
	CP		'h'
	JR		Z, .hlink
	; "gopher://" host ":" port "/" <type> selector
	LD		HL, SCHEME_GOPHER
	LD		DE, PREVIEW_BUF
	CALL	COPYZ
	LD		HL, (p_host)
	CALL	PV_APPEND
	LD		A, ':'
	LD		(DE), A
	INC		DE
	LD		HL, (p_port)
	CALL	PV_APPEND
	LD		A, '/'
	LD		(DE), A
	INC		DE
	LD		A, (row_type)
	LD		(DE), A
	INC		DE
	LD		HL, (p_sel)
	CALL	PV_APPEND
	JR		.show
.hlink
	LD		HL, (p_sel)				; type 'h': show the URL itself
	CALL	STRIP_URL_PREFIX
	LD		DE, PREVIEW_BUF
	CALL	PV_APPEND
.show
	XOR		A
	LD		(DE), A					; NUL-terminate PREVIEW_BUF
	LD		A, 1
	LD		(preview_shown), A
	LD		HL, PREVIEW_BUF
	JP		SET_STATUS

; Append ASCIIZ HL to DE, stopping at the NUL or near the end of PREVIEW_BUF (so
; the status line never overflows the row). DE left at the write position.
PV_APPEND
	LD		A, D
	CP		high (PREVIEW_BUF + 74)
	JR		C, .go
	LD		A, E
	CP		low (PREVIEW_BUF + 74)
	RET		NC						; reached the cap
.go
	LD		A, (HL)
	OR		A
	RET		Z
	LD		(DE), A
	INC		DE
	INC		HL
	JR		PV_APPEND

; ------------------------------------------------------
; Backspace: return to the previous page. The previous document is cached in
; history (its page chain), so this is instant - no network re-fetch.
; ------------------------------------------------------
ON_BACK
	LD		A, (hist_sp)
	OR		A
	JP		Z, MAINLOOP
	CALL	DOC.RESET				; free the current document's pages
	CALL	POP_HIST				; restore the cached previous doc (pages + view)
	CALL	CLAMP_SEL
	CALL	REDRAW_FULL
	CALL	SHOW_DOC_STATUS
	JP		MAINLOOP

; ------------------------------------------------------
; Bookmarks (Ctrl+B = open, Ctrl+D = add the current page). The bookmarks live in
; a gopher-format file BOOKMARK.GPH next to the EXE (8.3 name; we chdir'd into the
; EXE dir at startup, so a relative name resolves there). Each line is a normal
; type-1 menu record, so opening the file just browses it like any other page.
; ------------------------------------------------------
BM_FILE			DB "BOOKMARK.GPH", 0

; Ctrl+B: open BOOKMARK.GPH as a local menu page. Pushes history (so Backspace
; returns to where you were) and detaches the current doc, like following a link.
ON_BOOKMARKS
	CALL	PUSH_HIST				; cache the current page (nav + its doc pages)
	CALL	DOC.NEW					; detach those pages; start a fresh empty doc
	XOR		A
	LD		(cur_kind), A			; 0 = local page (no "Loaded N bytes" status)
	LD		A, '1'
	LD		(DOC_TYPE_CUR), A		; bookmarks render as a gopher menu
	LD		HL, MSG_BM_TITLE
	LD		DE, DOC_TITLE
	LD		B, TITLE_MAX
	CALL	STRCPYN
	LD		HL, 0
	LD		(HOST_CUR), HL			; empty host marks a local page (not bookmarkable)
	LD		HL, BM_FILE
	CALL	LOAD_DISK_GPH			; load the file into the doc; CF=1 absent/empty
	JR		NC, .have
	LD		HL, BM_EMPTY_DOC		; no bookmarks yet -> a friendly placeholder page
	LD		BC, BM_EMPTY_LEN
	CALL	DOC.APPEND
.have
	CALL	INVALIDATE_NET			; re-init the ESP before the next fetch: time spent on
									; this local page can leave the cached session stale
	CALL	DOC.COUNT_LINES
	LD		HL, 0
	LD		(sel_index), HL
	LD		(top_index), HL
	CALL	REDRAW_FULL
	CALL	SHOW_DOC_STATUS
	JP		MAINLOOP

; Ctrl+D: append the current page to BOOKMARK.GPH as a type-1 gopher record
; "<type><title> TAB <selector> TAB <host> TAB <port> CRLF". Only network pages
; have a host to bookmark; the home/bookmarks pages (empty host) are skipped.
ON_ADD_BOOKMARK
	LD		A, (HOST_CUR)
	OR		A
	JR		Z, .nothing
	CALL	BUILD_BM_LINE			; -> BM_LINE, BC = byte count
	CALL	APPEND_BM_LINE			; create/append BOOKMARK.GPH; CF=1 on disk error
	PUSH	AF						; force a re-init before the next fetch (the cached ESP
	CALL	INVALIDATE_NET			; session may go stale here); preserve the write's CF
	POP		AF
	JR		C, .fail
	LD		HL, MSG_BM_ADDED
	JR		.show
.nothing
	LD		HL, MSG_BM_NONE
	JR		.show
.fail
	LD		HL, MSG_BM_FAIL
.show
	CALL	SET_STATUS				; CALL (not JP): SET_STATUS RETs, we JP to the loop
	JP		MAINLOOP

; Build the bookmark line for the current page into BM_LINE. Out: BC = length.
; DOC_TITLE is in WIN1; SEL_CUR/HOST_CUR/PORT_CUR are in the WIN2 scratch page -
; COPYZ reads either window fine.
BUILD_BM_LINE
	LD		DE, BM_LINE
	LD		A, (DOC_TYPE_CUR)		; gopher type byte
	LD		(DE), A
	INC		DE
	LD		HL, DOC_TITLE			; display text
	CALL	COPYZ
	LD		A, 9					; TAB
	LD		(DE), A
	INC		DE
	LD		HL, SEL_CUR				; selector
	CALL	COPYZ
	LD		A, 9
	LD		(DE), A
	INC		DE
	LD		HL, HOST_CUR			; host
	CALL	COPYZ
	LD		A, 9
	LD		(DE), A
	INC		DE
	LD		HL, PORT_CUR			; port
	CALL	COPYZ
	LD		A, 13					; CRLF (NEXT_LINE tolerates CRLF or LF)
	LD		(DE), A
	INC		DE
	LD		A, 10
	LD		(DE), A
	INC		DE
	LD		HL, BM_LINE				; BC = DE - BM_LINE
	EX		DE, HL					; HL = end, DE = start
	OR		A
	SBC		HL, DE
	LD		B, H
	LD		C, L
	RET

; Append BM_LINE (BC bytes) to BOOKMARK.GPH, creating the file if needed.
; Out: CF=1 on a disk error (create/write failed).
APPEND_BM_LINE
	PUSH	BC						; save the length across the open/create
	LD		HL, BM_FILE
	LD		A, FM_READ_WRITE
	LD		C, DSS_OPEN_FILE
	RST		DSS						; -> A=handle, CF=1 if not found
	JR		NC, .opened
	LD		HL, BM_FILE				; first bookmark: create the file (#0A, the
	LD		A, FA_ARCHIVE			; create/overwrite call proven by the download path)
	LD		C, FILE.DSS_CREATE_OVR
	RST		DSS						; -> A=handle, CF=1 error
	JR		C, .err
.opened
	LD		(bm_fm), A
	LD		B, SEEK_END				; append: position at end of file
	LD		HL, 0
	LD		IX, 0
	LD		C, DSS_MOVE_FP
	RST		DSS
	POP		BC						; restore the line length
	PUSH	BC
	LD		D, B
	LD		E, C					; DE = size
	LD		HL, BM_LINE
	LD		A, (bm_fm)
	LD		C, DSS_WRITE
	RST		DSS						; HL=buf, DE=size, A=handle; CF=1 error
	PUSH	AF						; keep the write's CF across CLOSE
	LD		A, (bm_fm)
	LD		C, DSS_CLOSE_FILE
	RST		DSS
	POP		AF
	POP		BC
	RET
.err
	POP		BC
	SCF
	RET
bm_fm			DB 0

; ------------------------------------------------------
; Built-in home page (no network). Loaded into the doc like any fetched page.
; ------------------------------------------------------
LOAD_HOME
	CALL	DOC.RESET
	XOR		A
	LD		(cur_kind), A
	LD		A, '1'
	LD		(DOC_TYPE_CUR), A
	LD		HL, MSG_TITLE			; default header title for the home page
	LD		DE, DOC_TITLE
	LD		B, TITLE_MAX
	CALL	STRCPYN
	LD		HL, 0
	LD		(HOST_CUR), HL			; empty host marks the home page
	; priority: an external INDEX.GPH next to the EXE (user override) wins over the
	; copy appended to GOPHER.EXE, which wins over the tiny built-in stub.
	CALL	LOAD_HOME_DISK			; external INDEX.GPH in the EXE directory
	JR		NC, .counted
	CALL	LOAD_HOME_FILE			; the copy appended to GOPHER.EXE
	JR		NC, .counted
	LD		HL, WELCOME_DOC			; fallback: tiny built-in stub
	LD		BC, WELCOME_LEN
	CALL	DOC.APPEND
.counted
	CALL	DOC.COUNT_LINES
	OR		A
	RET

; Try to load an external INDEX.GPH from the EXE directory (we chdir'd there at
; startup, so a relative name resolves next to GOPHER.EXE). This lets the user
; override the home page without rebuilding. Out: CF=0 loaded (>0 B), CF=1 absent/
; empty.
HOME_FILE		DB "INDEX.GPH", 0
LOAD_HOME_DISK
	LD		HL, HOME_FILE
	; fall through into LOAD_DISK_GPH

; Open the ASCIIZ gopher file named in HL (relative to the EXE dir, where we
; chdir'd at startup) and load its whole contents into the current document.
; Out: CF=0 loaded (>0 B), CF=1 absent/empty. Shared by the home page and the
; bookmarks page (Ctrl+B).
LOAD_DISK_GPH
	LD		A, FM_READ
	LD		C, DSS_OPEN_FILE
	RST		DSS						; HL=name, A=mode -> A=handle, CF=1 not found
	RET		C
	LD		(disk_fm), A
	LD		B, SEEK_END
	LD		HL, 0
	LD		IX, 0
	LD		C, DSS_MOVE_FP
	RST		DSS						; HL:IX = size
	PUSH	IX
	POP		HL						; HL = size low 16 (assume < 64 KB)
	LD		A, H
	OR		L
	JR		Z, .empty				; empty file -> fall back to the appended copy
	LD		(hf_rem), HL
	LD		A, (disk_fm)			; rewind to the start
	LD		B, 0					; SEEK_SET
	LD		HL, 0
	LD		IX, 0
	LD		C, DSS_MOVE_FP
	RST		DSS
	LD		A, (disk_fm)
	CALL	READ_INTO_DOC			; hf_rem bytes -> doc
	LD		A, (disk_fm)
	LD		C, DSS_CLOSE_FILE
	RST		DSS
	OR		A						; CF=0
	RET
.empty
	LD		A, (disk_fm)
	LD		C, DSS_CLOSE_FILE
	RST		DSS
	SCF
	RET

; Read the home page that the Makefile appended to GOPHER.EXE into the current doc.
; A loader EXE leaves its own file open (FM captured from (IX-3) into home_fm at
; START); the appended bytes begin at file offset HOME_OFFSET = 0x200 + image size.
; We SEEK_END for the file size, take the tail (size - HOME_OFFSET) and read it.
; Out: CF=0 loaded (>0 B), CF=1 = no handle / nothing appended.
HOME_OFFSET		EQU 0x200 + IMAGE_END - LOAD_ADDR
LOAD_HOME_FILE
	LD		A, (home_fm)
	CP		FILE.NO_HANDLE
	JR		Z, .fail				; not a loader EXE / older DSS -> use the stub
	LD		B, SEEK_END
	LD		HL, 0
	LD		IX, 0
	LD		C, DSS_MOVE_FP
	RST		DSS						; HL:IX = file size
	PUSH	IX
	POP		HL						; HL = size low 16 (home page keeps the file < 64 KB)
	LD		DE, HOME_OFFSET
	OR		A
	SBC		HL, DE					; HL = appended byte count
	JR		Z, .fail
	JR		C, .fail
	LD		(hf_rem), HL
	LD		A, (home_fm)			; seek to the start of the appended data
	LD		B, 0					; SEEK_SET
	LD		HL, 0
	LD		IX, HOME_OFFSET
	LD		C, DSS_MOVE_FP
	RST		DSS
	LD		A, (home_fm)
	CALL	READ_INTO_DOC
	OR		A						; CF=0 (loaded; leave the EXE file open)
	RET
.fail
	SCF
	RET

; Read (hf_rem) bytes from the open file handle in A into the current document, in
; STAGE-sized chunks (STAGE is WIN2; DOC.APPEND time-shares WIN3, no ISA involved).
; Assumes the file is already positioned at the first byte to read.
READ_INTO_DOC
	LD		(rid_fm), A
.rl
	LD		HL, (hf_rem)
	LD		A, H
	OR		L
	RET		Z						; done
	LD		DE, STAGE_SIZE			; chunk = min(remaining, STAGE_SIZE)
	OR		A
	SBC		HL, DE
	JR		NC, .full
	LD		DE, (hf_rem)			; remaining < STAGE_SIZE -> last chunk
.full
	PUSH	DE
	LD		HL, STAGE
	LD		A, (rid_fm)
	LD		C, DSS_READ_FILE
	RST		DSS						; read DE bytes into STAGE
	POP		DE
	PUSH	DE
	LD		HL, STAGE
	LD		B, D
	LD		C, E
	CALL	DOC.APPEND				; append the chunk to the doc
	POP		DE
	LD		HL, (hf_rem)
	OR		A
	SBC		HL, DE
	LD		(hf_rem), HL
	JR		.rl
hf_rem			DW 0
disk_fm			DB 0
rid_fm			DB 0

; ------------------------------------------------------
; Fetch HOST_CUR/SEL_CUR/PORT_CUR into a fresh document. CF=1 on error
; (message pointer left in last_err). NET.INIT runs once and is cached.
; ------------------------------------------------------
DO_FETCH
	CALL	DOC.RESET
	XOR		A
	LD		(WCOMMON.CANCELLED), A	; clear any stale cancel flag before we start
	CALL	SHOW_FETCHING
	LD		A, (net_inited)
	OR		A
	JR		NZ, .haveinit
	CALL	NET.INIT				; AT/connect waits poll Esc/Ctrl+Z internally
	JR		C, .e_init
	LD		A, 1
	LD		(net_inited), A
.haveinit
	LD		HL, HOST_CUR
	LD		DE, PORT_CUR
	CALL	NET.CONNECT
	JR		C, .e_conn
	CALL	BUILD_REQ				; HL=REQ_BUF, BC=len
	CALL	NET.SEND
	JR		C, .e_send
	CALL	RECV_LOOP				; appends every block into the document
	JR		C, .e_cancel			; cancelled mid-download
	CALL	NET.CLOSE
	CALL	DOC.COUNT_LINES
	LD		HL, (DOC.doc_lines)
	LD		A, H
	OR		L
	JR		Z, .e_empty
	OR		A
	RET
.e_cancel
	CALL	NET.CLOSE
	LD		HL, ERR_CANCEL
	JP		FETCH_ERR
.e_init
	LD		HL, ERR_INIT
	JP		FETCH_ERR
.e_conn
	CALL	NET.CLOSE
	LD		HL, ERR_CONN
	JP		FETCH_ERR
.e_send
	CALL	NET.CLOSE
	LD		HL, ERR_SEND
	JP		FETCH_ERR
.e_empty
	LD		HL, ERR_EMPTY
	JP		FETCH_ERR

; HL = default error message; if a user cancel was flagged by the kit
; (WCOMMON.CANCELLED, set on Esc/Ctrl+Z), report "Cancelled" instead. CF=1.
FETCH_ERR
	LD		A, (WCOMMON.CANCELLED)
	OR		A
	JR		Z, .set
	LD		HL, ERR_CANCEL
.set
	LD		(last_err), HL
	SCF
	RET

; Receive blocks into STAGE and append to the document until the connection
; closes / times out, or the document hits its page cap.
; Receive into STAGE and append to the document. Brackets the slow append/redraw
; with RX pause (drops RTS so the ESP holds its TX → no UART FIFO overrun), and
; shows the running downloaded size on the status bar.
RECV_LOOP
.l
	LD		A, (DOC.doc_trunc)
	OR		A
	JR		NZ, .end
	CALL	NET.RX_RESUME			; raise RTS: let the ESP stream
	LD		HL, STAGE
	LD		BC, STAGE_SIZE
	LD		DE, RECV_TIMEOUT
	CALL	NET.RECV				; its byte waits poll Esc/Ctrl+Z; CF on end/cancel
	PUSH	AF
	CALL	NET.RX_PAUSE			; drop RTS: ESP holds while we store + draw
	POP		AF
	JR		C, .end					; closed / timeout / error / cancelled
	LD		A, B
	OR		C
	JR		Z, .end					; no more data
	LD		HL, STAGE
	CALL	DOC.APPEND				; BC = bytes; doc size grows with it
	CALL	SHOW_PROGRESS			; reads the size from the doc itself
	CALL	CLOCK_TICK				; ISA is closed here (post RX_PAUSE) - DSS is safe
	JR		.l
.end
	CALL	NET.RX_RESUME			; leave RX resumed for the CLOSE handshake
	LD		A, (WCOMMON.CANCELLED)	; CF=1 only if the user cancelled the download
	OR		A
	RET		Z						; normal end (CF=0)
	SCF
	RET

; Status-bar download progress: "Loading <n> bytes" (<1 KB) or "Loading <n> KB".
; Gopher has no content-length, so we show the downloaded amount, not a percent.
SHOW_PROGRESS
	CALL	STATUS_HOME				; clear status row, cursor at col 1
	LD		HL, MSG_LOADING
	CALL	TERM.PUTS
	JP		PUT_SIZE

; After a fetch: "Loaded <size>" plus " - INCOMPLETE" if the gopher "." terminator
; was never received (a truncated transfer).
SHOW_LOADED
	CALL	STATUS_HOME
	LD		HL, MSG_LOADED
	CALL	TERM.PUTS
	CALL	PUT_SIZE
	LD		A, (DOC.doc_complete)
	OR		A
	RET		NZ						; complete -> done
	LD		HL, MSG_INCOMPLETE
	JP		TERM.PUTS

; Status line for the freshly shown document: size+completeness for a network
; page, the key help for the built-in home page.
SHOW_DOC_STATUS
	LD		A, (cur_kind)
	OR		A
	JP		NZ, SHOW_LOADED
	; home page: warn up front if the network is not configured (NETUP not run),
	; so the user knows before clicking a link - otherwise show the key help.
	CALL	NET.CHECK_NET_UP		; fast env check (NET=WIFI / NET_ESP_HW), no UART
	JR		C, .nonet
	LD		HL, MSG_STATUS
	JP		SET_STATUS
.nonet
	LD		HL, MSG_NONET
	JP		SET_STATUS

; Clear the status row (ATTR_STATUS) and move the cursor to its column 1.
STATUS_HOME
	LD		D, STATUS_ROW
	LD		E, 0
	LD		H, 1
	LD		L, SCR_W
	LD		B, ATTR_STATUS
	LD		A, ' '
	CALL	TERM.FILL
	LD		D, STATUS_ROW
	LD		E, 1
	JP		TERM.LOCATE

; Print the current document size at the cursor as "<n> bytes" (<1 KB) or "<n> KB".
; Reads it from the live doc (DOC.SIZE), so it is right both while loading and for
; a restored cached page on Back.
PUT_SIZE
	CALL	DOC.SIZE				; HL = low 16, A = high 8
	LD		(recv_lo), HL
	LD		(recv_hi), A
; Format the 24-bit size in recv_lo/recv_hi at the cursor (used by downloads too).
PUT_SIZE_RV
	LD		A, (recv_hi)
	OR		A
	JR		NZ, .kb					; >= 64 KB -> KB
	LD		HL, (recv_lo)
	LD		DE, 1024
	OR		A
	SBC		HL, DE					; lo - 1024; CF=1 if < 1 KB
	JR		NC, .kb
	LD		HL, (recv_lo)			; show raw bytes
	LD		DE, NUMBUF
	CALL	UTIL.UTOA
	LD		HL, SUFFIX_B
	JR		.draw
.kb
	; kb = (recv_hi << 6) + (recv_lo >> 10)
	LD		A, (recv_hi)
	LD		L, A
	LD		H, 0
	ADD		HL, HL
	ADD		HL, HL
	ADD		HL, HL
	ADD		HL, HL
	ADD		HL, HL
	ADD		HL, HL					; HL = recv_hi * 64
	LD		A, (recv_lo + 1)		; recv_lo >> 8
	SRL		A
	SRL		A						; >> 10 total (0..63)
	LD		E, A
	LD		D, 0
	ADD		HL, DE					; HL = KB
	LD		DE, NUMBUF
	CALL	UTIL.UTOA
	LD		HL, SUFFIX_KB
.draw
	LD		(prog_suffix), HL
	LD		HL, NUMBUF
	CALL	TERM.PUTS
	LD		HL, (prog_suffix)
	JP		TERM.PUTS

; Build the gopher request (SEL_CUR + CRLF) in REQ_BUF. Out: HL=REQ_BUF, BC=len.
BUILD_REQ
	LD		HL, SEL_CUR
; Build a request from the selector at HL. Out: HL=REQ_BUF, BC=len.
BUILD_REQ_HL
	LD		DE, REQ_BUF
	CALL	COPYZ					; copies without the NUL; DE left at end
	LD		A, 13
	LD		(DE), A
	INC		DE
	LD		A, 10
	LD		(DE), A
	INC		DE
	LD		HL, REQ_BUF
	EX		DE, HL					; HL=end, DE=REQ_BUF
	OR		A
	SBC		HL, DE					; HL = length
	LD		B, H
	LD		C, L
	LD		HL, REQ_BUF
	RET

; ------------------------------------------------------
; Binary / media downloads.
; ------------------------------------------------------
; A = gopher item type. Out: ZF=1 if it is a downloadable binary/media type.
; (9 binary, 5 DOS archive, g GIF, I image, s sound, ; video, d document, p PNG.)
IS_BIN_TYPE
	PUSH	BC
	PUSH	HL
	LD		C, A
	LD		HL, BIN_TYPES
.l
	LD		A, (HL)
	OR		A
	JR		Z, .no
	CP		C
	JR		Z, .yes
	INC		HL
	JR		.l
.yes
	XOR		A						; ZF=1
	JR		.done
.no
	OR		1						; ZF=0
.done
	POP		HL
	POP		BC
	RET
BIN_TYPES		DB "95gIs;dp", 0

; Stream DL_SEL from DL_HOST:DL_PORT into the file DL_PATH. The running and final
; size accumulate into recv_lo/recv_hi (the document is not touched). CF=0 ok,
; CF=1 on error (last_err set; FETCH_ERR maps a user cancel to "Cancelled").
DOWNLOAD
	XOR		A
	LD		(WCOMMON.CANCELLED), A	; clear any stale cancel flag
	LD		HL, 0
	LD		(recv_lo), HL
	LD		(recv_hi), A			; zero the byte counter
	CALL	SHOW_FETCHING
	LD		A, (net_inited)
	OR		A
	JR		NZ, .haveinit
	CALL	NET.INIT
	JR		C, .e_init
	LD		A, 1
	LD		(net_inited), A
.haveinit
	LD		HL, DL_HOST
	LD		DE, DL_PORT
	CALL	NET.CONNECT
	JR		C, .e_conn
	LD		HL, DL_SEL
	CALL	BUILD_REQ_HL			; HL=REQ_BUF, BC=len
	CALL	NET.SEND
	JR		C, .e_send
	LD		HL, DL_DIRMK			; mkdir <exe-dir>\DOWNLOAD (ignore "exists")
	CALL	FILE.ENSURE_DIR
	LD		HL, DL_PATH
	CALL	FILE.CREATE
	JR		C, .e_file
	CALL	DL_RECV_LOOP			; writes blocks to the file; CF=1 on cancel/disk
	PUSH	AF
	CALL	FILE.CLOSE
	CALL	NET.CLOSE
	POP		AF
	RET		NC						; success (CF=0)
	LD		A, (WCOMMON.CANCELLED)
	OR		A
	JR		NZ, .e_cancel			; cancelled mid-download
	LD		HL, ERR_DISK			; otherwise a disk write failed
	JP		FETCH_ERR
.e_cancel
	LD		HL, ERR_CANCEL
	JP		FETCH_ERR
.e_init
	LD		HL, ERR_INIT
	JP		FETCH_ERR
.e_conn
	CALL	NET.CLOSE
	LD		HL, ERR_CONN
	JP		FETCH_ERR
.e_send
	CALL	NET.CLOSE
	LD		HL, ERR_SEND
	JP		FETCH_ERR
.e_file
	CALL	NET.CLOSE
	LD		HL, ERR_DISK
	JP		FETCH_ERR

; Receive into the 8 KB DL_BUF accumulator and flush to the open file in
; 512-byte-aligned chunks until the connection closes/times out, the user
; cancels, or a write fails. Batching cuts the FAT cost: instead of one small
; unaligned write per ~2 KB recv (each touching a partial sector), we write
; whole 512-byte-aligned blocks and carry the sub-sector remainder forward.
; Mirrors RECV_LOOP's RTS-flow-control bracketing (RTS up to stream, down to
; write/draw). Out: CF=0 normal end, CF=1 cancel/disk error.
;
; Each NET.RECV is given ALL the free space in DL_BUF; the kit reads back-to-back
; +IPD blocks until it is nearly full or the stream pauses, decrements RECV_REMAIN
; per byte (so it never overruns the buffer) and carries a partial IPD payload to
; the next call - no bytes are lost.
DL_FLUSH_HI		EQU DL_BUF_SIZE - 2048	; 2048: flush once this full (room for 1+ IPD)
DL_RECV_LOOP
	LD		HL, 0
	LD		(dl_fill), HL			; accumulator empty
.l
	CALL	NET.RX_RESUME			; raise RTS: let the ESP stream
	LD		HL, (dl_fill)
	LD		DE, DL_BUF
	ADD		HL, DE					; HL = DL_BUF + dl_fill (dest)
	PUSH	HL
	LD		HL, DL_BUF_SIZE
	LD		DE, (dl_fill)
	OR		A
	SBC		HL, DE					; HL = free space = SIZE - fill
	LD		B, H
	LD		C, L					; BC = space
	POP		HL						; HL = dest
	LD		DE, RECV_TIMEOUT
	CALL	NET.RECV
	PUSH	AF
	CALL	NET.RX_PAUSE			; drop RTS while we (maybe) write + draw
	POP		AF
	JR		C, .end					; closed / timeout / error / cancelled
	LD		A, B
	OR		C
	JR		Z, .end					; no more data
	CALL	DL_ADD					; recv_lo/recv_hi += BC (received) - preserves BC
	LD		HL, (dl_fill)
	ADD		HL, BC
	LD		(dl_fill), HL			; dl_fill += received
	CALL	DL_PROGRESS
	CALL	CLOCK_TICK				; ISA closed here (post RX_PAUSE) - DSS is safe
	LD		HL, (dl_fill)
	LD		DE, DL_FLUSH_HI
	OR		A
	SBC		HL, DE
	JR		C, .l					; below high-water -> keep accumulating
	CALL	DL_FLUSH_ALIGNED		; write (fill & ~511) bytes, carry the remainder
	JR		C, .werr
	JR		.l
.end
	; flush whatever is left (one final, possibly sub-sector, write)
	LD		HL, (dl_fill)
	LD		A, H
	OR		L
	JR		Z, .tail_done
	LD		B, H
	LD		C, L					; BC = leftover bytes
	LD		HL, DL_BUF
	CALL	FILE.WRITE
	JR		C, .werr
.tail_done
	CALL	NET.RX_RESUME			; resume for the CLOSE handshake
	LD		A, (WCOMMON.CANCELLED)	; CF=1 only if the user cancelled
	OR		A
	RET		Z						; normal end (CF=0)
	SCF
	RET
.werr
	CALL	NET.RX_RESUME
	SCF								; CF=1, CANCELLED=0 -> caller reports disk error
	RET

; Write the 512-byte-aligned prefix of DL_BUF to disk, then shift the sub-sector
; remainder down to the front of DL_BUF. In: dl_fill = bytes buffered. Out:
; dl_fill = leftover (< 512); CF=1 on disk write error. Trashes A/BC/DE/HL.
DL_FLUSH_ALIGNED
	LD		HL, (dl_fill)
	LD		A, H
	AND		0xFE					; nwrite = dl_fill & 0xFE00 (multiple of 512)
	LD		H, A
	LD		L, 0
	LD		A, H
	OR		L
	RET		Z						; nothing aligned yet (CF=0)
	LD		B, H
	LD		C, L					; BC = nwrite
	PUSH	BC
	LD		HL, DL_BUF
	CALL	FILE.WRITE				; HL=buf, BC=len
	POP		DE						; DE = nwrite
	RET		C						; disk error
	LD		HL, (dl_fill)
	OR		A
	SBC		HL, DE					; HL = remainder = fill - nwrite
	LD		(dl_fill), HL
	LD		A, H
	OR		L
	RET		Z						; no remainder -> done (CF=0)
	LD		B, H
	LD		C, L					; BC = remainder
	LD		HL, DL_BUF
	ADD		HL, DE					; HL = DL_BUF + nwrite (src tail)
	LD		DE, DL_BUF				; dst = front
	LDIR
	OR		A						; CF=0
	RET

; recv_lo/recv_hi += BC (24-bit running total).
DL_ADD
	LD		HL, (recv_lo)
	ADD		HL, BC
	LD		(recv_lo), HL
	RET		NC
	LD		A, (recv_hi)
	INC		A
	LD		(recv_hi), A
	RET

; Status-bar download progress: "Saving <n> bytes/KB".
DL_PROGRESS
	CALL	STATUS_HOME
	LD		HL, MSG_SAVING
	CALL	TERM.PUTS
	JP		PUT_SIZE_RV				; formats recv_lo/recv_hi at the cursor

; Final status after a successful download: "Saved <n> KB to <path>".
SHOW_SAVED
	CALL	STATUS_HOME
	LD		HL, MSG_SAVED
	CALL	TERM.PUTS
	CALL	PUT_SIZE_RV
	LD		HL, MSG_TO
	CALL	TERM.PUTS
	LD		HL, DL_PATH
	JP		TERM.PUTS

; After a successful download: if GOPHER.CFG maps the file's extension to a
; program, optionally ask the user (unless the "skip_ask_for_exec" setting is on)
; and launch it via Dss.Exec with %file% = the saved file's path.
MAYBE_OPEN_DOWNLOAD
	CALL	DL_EXT_PTR				; HL = extension of DL_NAME (empty if none)
	CALL	CFG.VIEWER_FOR_EXT		; HL=ext -> DE=command template, CF=1 if none
	RET		C						; no association -> leave the "Saved ..." status
	LD		(open_tpl), DE
	CALL	SKIP_ASK				; CF=1 -> launch without asking
	JR		C, .launch
	CALL	CONFIRM_OPEN			; CF=1 -> user declined
	JR		NC, .launch
	CALL	SHOW_DOC_STATUS			; restore the status line after the prompt
	RET
.launch
	CALL	BUILD_FILE_ABS			; FILE_ABS = absolute path of the saved file
	LD		HL, (open_tpl)
	LD		DE, FILE_ABS
	CALL	CFG.BUILD_CMD			; HL = CMD_BUF ("%file%" expanded): "prog arg"
	CALL	EXEC_PROGRAM			; run the viewer directly (full EXE path), like FN
	PUSH	AF						; CF = launch error
	CALL	REDRAW_FULL				; the viewer took over the screen - repaint
	POP		AF
	JR		C, .err
	CALL	SHOW_DOC_STATUS
	RET
.err
	LD		HL, MSG_EXEC_FAIL
	JP		SET_STATUS

; HL -> the extension of DL_NAME (the part after the last '.'); empty if none.
DL_EXT_PTR
	LD		HL, DL_NAME
	LD		BC, 0					; BC = ext pointer (after the last '.'), 0 = none
.l
	LD		A, (HL)
	OR		A
	JR		Z, .done
	CP		'.'
	JR		NZ, .next
	LD		B, H					; ext candidate = char after this '.'
	LD		C, L
	INC		BC
.next
	INC		HL
	JR		.l
.done
	LD		A, B
	OR		C
	JR		Z, .noext
	LD		H, B
	LD		L, C
	RET
.noext
	LD		HL, EMPTYSTR
	RET

; Build FILE_ABS = <EXE dir> + DL_PATH (absolute path of the saved file). If the
; EXE dir is unknown (AppInfo failed) EXE_DIR is empty and the path stays relative.
BUILD_FILE_ABS
	LD		HL, EXE_DIR
	LD		DE, FILE_ABS
	CALL	COPYZ					; copy dir (no NUL); DE -> end
	LD		HL, DL_PATH
	CALL	COPYZ					; append "DOWNLOAD\<name>"
	XOR		A
	LD		(DE), A
	RET

; CF=1 if the "skip_ask_for_exec" setting is truthy (launch without asking),
; CF=0 if absent/false (ask the user first).
SKIP_ASK
	LD		HL, KEY_SKIPASK
	CALL	CFG.SETTING				; DE = value, CF=1 if not set
	JR		C, .ask					; not set -> ask
	LD		A, (DE)					; truthy if it starts 1/y/Y/t/T
	CP		'1'
	JR		Z, .skip
	CP		'y'
	JR		Z, .skip
	CP		'Y'
	JR		Z, .skip
	CP		't'
	JR		Z, .skip
	CP		'T'
	JR		Z, .skip
.ask
	OR		A						; CF=0 -> ask the user
	RET
.skip
	SCF								; CF=1 -> launch without asking
	RET

; Ask whether to open the file. Out: CF=0 if yes (Y/y), CF=1 otherwise.
CONFIRM_OPEN
	LD		HL, MSG_OPEN_ASK
	CALL	SET_STATUS
	CALL	INP_WAIT_RELEASE
.poll
	CALL	CLOCK_TICK
	CALL	KBD.SCAN
	JR		Z, .poll
	CP		'Y'
	JR		Z, .yes
	CP		'y'
	JR		Z, .yes
	CALL	INP_WAIT_RELEASE
	SCF
	RET
.yes
	CALL	INP_WAIT_RELEASE
	OR		A						; CF=0
	RET

; Launch the program whose command line is in HL (program + args). Saves/restores
; SP (Dss.Exec changes it), re-maps our WIN2 scratch page and re-asserts 80x32 text
; on return (the child may have changed both). Out: A=exit code, CF=1 on launch
; error (FM idiom: HL=cmdline, BC=#0040).
; Clear the screen to the standard attributes (black paper, non-bright white
; ink = ATTR_NORM) and announce the program we are about to launch, so the
; external viewer starts from a clean, predictable console. In: HL = command
; line (lives in the WIN2 page, CFG_CMD_BUF). Preserves HL for the Dss.Exec that
; follows. (PChars prints fine straight from WIN2 - verified on target.)
SHOW_EXEC_BANNER
	PUSH	HL
	CALL	TERM.CLS				; black background, non-bright white text
	LD		DE, 0					; D=row 0, E=col 0
	CALL	TERM.LOCATE
	LD		HL, MSG_RUNEXT			; "Running external viewer:\r\n"
	CALL	TERM.PUTS
	POP		HL
	PUSH	HL						; HL = command line
	CALL	TERM.PUTS				; print the command line straight from WIN2
	LD		HL, MSG_CRLF			; end the line so the child starts on a fresh row
	CALL	TERM.PUTS
	POP		HL						; restore command pointer for Dss.Exec
	RET

EXEC_PROGRAM
	CALL	SHOW_EXEC_BANNER		; clean screen + "Running external viewer:" + cmd
	; Dss.Exec saves the parent's WIN1/WIN2/WIN3 page registers (and SP) and
	; restores them on return; our WIN2 page is a GetMem block tagged to our task,
	; so the child can't allocate over it. So the WIN2 runtime stack survives the
	; exec unchanged - no stack juggling needed. (exec_sp is just belt-and-braces;
	; it's a WIN1 var, valid to read whatever WIN2 holds.)
	LD		(exec_sp), SP
	LD		BC, 0x0040				; B=0 (short name), C=#40 (Dss.Exec)
	RST		DSS						; -> A=exit code, CF=1 error
	LD		SP, (exec_sp)
	PUSH	AF
	CALL	CHDIR_EXE				; cwd is process state (not a window) - restore it
	LD		A, DSS_VMOD_T80			; re-assert 80x32 text mode
	LD		C, DSS_SETVMOD
	RST		DSS
	; The child ran with the ISA card in an unknown state (DSS/Exec and the viewer
	; may have touched the ISA window / UART), so drop our cached "card is up"
	; flag; the next fetch re-runs NET.INIT (re-init UART + AT, drain stale bytes,
	; no ISA_RESET so the NETUP Wi-Fi session is preserved). Without this the next
	; TCP.OPEN talks to a disturbed card -> "Connect failed".
	CALL	INVALIDATE_NET
	POP		AF
	RET

; Drop the cached "ESP is initialised" flag so the next fetch re-runs NET.INIT
; (full UART re-init + AT + drain, no ISA_RESET -> Wi-Fi session preserved). This
; is a RECOVERY: a cached net_inited=1 makes a fetch skip init and reuse the open
; UART/ESP session; if that session has gone stale the connect hangs on
; "Fetching..." and, because the flag stays 1, never recovers ("link dies"). A
; forced re-init clears any stale UART/ESP state.
;   NOTE: this is NOT because file I/O corrupts the card. The kit brackets every
;   UART access with ISA_OPEN/ISA_CLOSE (which save/restore WIN3), so a file
;   read/write between network ops is safe - that's exactly why a chunked download
;   (interleaved RECV + FILE.WRITE on one open socket) works. EXEC_PROGRAM re-inits
;   for a different reason (a child program can reprogram the ISA card directly).
; Trashes A.
INVALIDATE_NET
	XOR		A
	LD		(net_inited), A
	RET

; Derive an 8.3 filename from the selector DL_SEL into DL_NAME, then build
; DL_PATH = "DOWNLOAD\<name>". Non-FAT chars are sanitised; an empty basename
; falls back to a default. Trashes A/BC/DE/HL.
MAKE_DLNAME
	; 1) find the basename start (after the last '/' or '\') in DE.
	LD		HL, DL_SEL
	LD		D, H
	LD		E, L
.fb
	LD		A, (HL)
	OR		A
	JR		Z, .fbdone
	CP		'/'
	JR		Z, .sep
	CP		'\'
	JR		Z, .sep
	INC		HL
	JR		.fb
.sep
	INC		HL
	LD		D, H
	LD		E, L					; basename start = char after the separator
	JR		.fb
.fbdone
	LD		A, (DE)
	OR		A
	JP		Z, .default				; empty basename
	; 2) copy up to 8 name chars (until '.' or end) into DL_NAME.
	EX		DE, HL					; HL = src basename
	LD		DE, DL_NAME				; dst
	LD		B, 8
.nloop
	LD		A, (HL)
	OR		A
	JR		Z, .namedone			; end, no extension
	CP		'.'
	JR		Z, .extstart
	CALL	SANITIZE_CH
	LD		(DE), A
	INC		DE
	INC		HL
	DJNZ	.nloop
	; name longer than 8: skip the rest until '.' or end
.skipname
	LD		A, (HL)
	OR		A
	JR		Z, .namedone
	CP		'.'
	JR		Z, .extstart
	INC		HL
	JR		.skipname
.extstart
	INC		HL						; skip the '.'
	LD		A, (HL)
	OR		A
	JR		Z, .namedone			; trailing dot, no extension
	LD		A, '.'
	LD		(DE), A
	INC		DE
	LD		B, 3
.eloop
	LD		A, (HL)
	OR		A
	JR		Z, .namedone
	CALL	SANITIZE_CH
	LD		(DE), A
	INC		DE
	INC		HL
	DJNZ	.eloop
.namedone
	XOR		A
	LD		(DE), A					; NUL-terminate DL_NAME
	JR		.buildpath
.default
	LD		HL, DEF_DLNAME
	LD		DE, DL_NAME
	LD		B, 16
	CALL	STRCPYN
.buildpath
	LD		HL, DL_DIRPFX			; "DOWNLOAD\"
	LD		DE, DL_PATH
	CALL	COPYZ					; DE -> end (no NUL)
	LD		HL, DL_NAME
	CALL	COPYZ
	XOR		A
	LD		(DE), A					; NUL-terminate DL_PATH
	RET

; Map A to a FAT-safe uppercase filename char (A-Z 0-9 - _ kept, else '_').
SANITIZE_CH
	CP		'a'
	JR		C, .chk
	CP		'z' + 1
	JR		NC, .chk
	SUB		0x20					; to uppercase
.chk
	CP		'0'
	JR		C, .bad
	CP		'9' + 1
	JR		C, .good
	CP		'A'
	JR		C, .bad
	CP		'Z' + 1
	JR		C, .good
	CP		'-'
	RET		Z
	CP		'_'
	RET		Z
.bad
	LD		A, '_'
.good
	RET

; ------------------------------------------------------
; Parse LINE_BUF into row_type + p_disp/p_sel/p_host/p_port (pointers into
; LINE_BUF). TABs are replaced with NUL; absent fields point at an empty string.
; ------------------------------------------------------
PARSE_ROW
	LD		DE, EMPTYSTR
	LD		(p_sel), DE
	LD		(p_host), DE
	LD		(p_port), DE
	LD		A, (DOC_TYPE_CUR)
	CP		'1'
	JR		Z, .menu
	; text document (type 0): the line is raw text, NO type byte and no TAB
	; fields - the whole line is the display.
	LD		HL, LINE_BUF
	LD		(p_disp), HL
	XOR		A
	LD		(row_type), A			; 0 = plain text line (non-selectable)
	RET
.menu
	LD		HL, LINE_BUF
	LD		A, (HL)
	LD		(row_type), A
	INC		HL
	LD		(p_disp), HL
	CALL	SCAN_FIELD				; end of display
	RET		NC						; info line: no further fields
	LD		(p_sel), HL
	CALL	SCAN_FIELD
	RET		NC
	LD		(p_host), HL
	CALL	SCAN_FIELD
	RET		NC
	LD		(p_port), HL
	RET

; Advance HL to the next field. If a TAB is found it is replaced with NUL and
; HL points past it (CF=1); at NUL, CF=0 (no more fields).
SCAN_FIELD
.l
	LD		A, (HL)
	OR		A
	JR		Z, .end
	CP		9
	JR		Z, .tab
	INC		HL
	JR		.l
.tab
	LD		(HL), 0
	INC		HL
	SCF
	RET
.end
	OR		A
	RET

; ------------------------------------------------------
; History: push current nav before following a link; pop to go back.
; ------------------------------------------------------
PUSH_HIST
	LD		A, (hist_sp)
	CP		HIST_MAX
	JR		C, .haveroom
	; full: free the oldest level's cached pages, then shift the array down
	LD		HL, HIST_DATA + HR_DOCSTATE
	CALL	DOC.FREE_STATE
	LD		HL, HIST_DATA + HR_SIZE
	LD		DE, HIST_DATA
	LD		BC, (HIST_MAX - 1) * HR_SIZE
	LDIR
	LD		A, HIST_MAX - 1
	LD		(hist_sp), A
.haveroom
	LD		A, (hist_sp)
	CALL	HREC_ADDR				; HL = record address
	PUSH	HL
	LD		A, (cur_kind)
	LD		(HL), A					; +HR_KIND
	POP		HL
	PUSH	HL
	LD		DE, HR_HOST
	ADD		HL, DE
	EX		DE, HL
	LD		HL, HOST_CUR
	LD		B, 64
	CALL	STRCPYN
	POP		HL
	PUSH	HL
	LD		DE, HR_PORT
	ADD		HL, DE
	EX		DE, HL
	LD		HL, PORT_CUR
	LD		B, 8
	CALL	STRCPYN
	POP		HL
	PUSH	HL
	LD		DE, HR_SEL
	ADD		HL, DE
	EX		DE, HL
	LD		HL, SEL_CUR
	LD		B, 200
	CALL	STRCPYN
	POP		HL
	PUSH	HL
	LD		DE, HR_TYPE
	ADD		HL, DE
	LD		A, (DOC_TYPE_CUR)
	LD		(HL), A
	POP		HL
	PUSH	HL
	LD		DE, HR_SELIDX
	ADD		HL, DE
	EX		DE, HL
	LD		HL, (sel_index)
	CALL	STORE_HL_DE
	POP		HL
	LD		DE, HR_TOPIDX
	ADD		HL, DE
	EX		DE, HL
	LD		HL, (top_index)
	CALL	STORE_HL_DE
	; title
	LD		A, (hist_sp)
	CALL	HREC_ADDR
	LD		DE, HR_TITLE
	ADD		HL, DE
	EX		DE, HL
	LD		HL, DOC_TITLE
	LD		B, TITLE_MAX
	CALL	STRCPYN
	; cache the document itself (page chain) so Back needs no re-fetch
	LD		A, (hist_sp)
	CALL	HREC_ADDR
	LD		DE, HR_DOCSTATE
	ADD		HL, DE
	CALL	DOC.SAVE_STATE
	LD		A, (hist_sp)
	INC		A
	LD		(hist_sp), A
	RET

POP_HIST
	LD		A, (hist_sp)
	OR		A
	RET		Z
	DEC		A
	LD		(hist_sp), A
	CALL	HREC_ADDR				; HL = record
	PUSH	HL
	LD		A, (HL)
	LD		(cur_kind), A
	POP		HL
	PUSH	HL
	LD		DE, HR_HOST
	ADD		HL, DE
	LD		DE, HOST_CUR
	LD		B, 64
	CALL	STRCPYN
	POP		HL
	PUSH	HL
	LD		DE, HR_PORT
	ADD		HL, DE
	LD		DE, PORT_CUR
	LD		B, 8
	CALL	STRCPYN
	POP		HL
	PUSH	HL
	LD		DE, HR_SEL
	ADD		HL, DE
	LD		DE, SEL_CUR
	LD		B, 200
	CALL	STRCPYN
	POP		HL
	PUSH	HL
	LD		DE, HR_TYPE
	ADD		HL, DE
	LD		A, (HL)
	LD		(DOC_TYPE_CUR), A
	POP		HL
	PUSH	HL
	LD		DE, HR_SELIDX
	ADD		HL, DE
	CALL	LOAD_HL_FROM_HL
	LD		(sel_index), HL
	POP		HL
	PUSH	HL
	LD		DE, HR_TOPIDX
	ADD		HL, DE
	CALL	LOAD_HL_FROM_HL
	LD		(top_index), HL
	POP		HL
	LD		DE, HR_TITLE
	ADD		HL, DE
	LD		DE, DOC_TITLE
	LD		B, TITLE_MAX
	CALL	STRCPYN
	; restore the cached document (page chain) - no re-fetch
	LD		A, (hist_sp)
	CALL	HREC_ADDR
	LD		DE, HR_DOCSTATE
	ADD		HL, DE
	CALL	DOC.LOAD_STATE
	RET

; HL = HIST_DATA + A*HR_SIZE
HREC_ADDR
	LD		HL, HIST_DATA
	OR		A
	RET		Z
	LD		B, A
	LD		DE, HR_SIZE
.l
	ADD		HL, DE
	DJNZ	.l
	RET

; Store HL (16-bit little-endian) at (DE).
STORE_HL_DE
	LD		A, L
	LD		(DE), A
	INC		DE
	LD		A, H
	LD		(DE), A
	RET

; Load 16-bit little-endian from (HL) into HL.
LOAD_HL_FROM_HL
	LD		A, (HL)
	INC		HL
	LD		H, (HL)
	LD		L, A
	RET

; ------------------------------------------------------
; String helpers.
; ------------------------------------------------------
; Copy ASCIIZ HL->DE including the NUL, up to B-1 chars then forced NUL.
STRCPYN
.l
	LD		A, B
	CP		1
	JR		Z, .term
	LD		A, (HL)
	LD		(DE), A
	OR		A
	RET		Z
	INC		HL
	INC		DE
	DEC		B
	JR		.l
.term
	XOR		A
	LD		(DE), A
	RET

; Copy ASCIIZ HL->DE without the NUL. Out: DE past last char, HL past NUL.
COPYZ
.l
	LD		A, (HL)
	INC		HL
	OR		A
	RET		Z
	LD		(DE), A
	INC		DE
	JR		.l

; ------------------------------------------------------
; Status bar helpers.
; ------------------------------------------------------
; Fill the status row and print the ASCIIZ message in HL.
SET_STATUS
	PUSH	HL
	LD		D, STATUS_ROW
	LD		E, 0
	LD		H, 1
	LD		L, SCR_W
	LD		B, ATTR_STATUS
	LD		A, ' '
	CALL	TERM.FILL
	LD		D, STATUS_ROW
	LD		E, 1
	CALL	TERM.LOCATE
	POP		HL
	JP		TERM.PUTS

SHOW_FETCHING
	LD		HL, MSG_FETCHING
	JP		SET_STATUS

SHOW_ERROR
	LD		HL, (last_err)
	JP		SET_STATUS

; ------------------------------------------------------
; Single-line text input on the status row (used for type-7 search queries).
; In:  HL = prompt ASCIIZ, DE = destination buffer, B = buffer size (incl. NUL).
; Out: CF=0 submitted (Enter), CF=1 cancelled (Esc). Buffer is ASCIIZ either way.
; Uses ScanKey (A=char code, E=ASCII) with a wait-for-release debounce so a held
; key registers once. The buffer is kept NUL-terminated as it is edited so the
; redraw can print it directly.
; ------------------------------------------------------
INPUT_LINE
	LD		(in_prompt), HL
	LD		(in_buf), DE
	LD		A, B
	DEC		A						; reserve one byte for the NUL
	LD		(in_max), A
	XOR		A
	LD		(in_pos), A
	LD		(DE), A					; start empty
	CALL	INP_WAIT_RELEASE		; don't read the Enter that opened the prompt
.redraw
	CALL	INP_DRAW
.poll
	CALL	CLOCK_TICK				; keep the clock live while typing
	CALL	KBD.SCAN
	JR		Z, .poll
	CP		KEY_ENTER
	JR		Z, .submit
	CP		KEY_ESC
	JR		Z, .cancel
	CP		KEY_BS
	JR		Z, .back
	LD		A, E					; ASCII; accept printable 0x20..0x7E only
	CP		0x20
	JR		C, .ignore
	CP		0x7F
	JR		NC, .ignore
	LD		A, (in_pos)
	LD		HL, in_max
	CP		(HL)
	JR		Z, .ignore				; buffer full
	LD		HL, (in_buf)
	LD		C, A					; A = in_pos
	LD		B, 0
	ADD		HL, BC
	LD		A, E
	LD		(HL), A					; store the char
	INC		HL
	XOR		A
	LD		(HL), A					; keep it NUL-terminated
	LD		HL, in_pos
	INC		(HL)
	CALL	INP_WAIT_RELEASE
	JR		.redraw
.back
	LD		A, (in_pos)
	OR		A
	JR		Z, .ignore				; nothing to erase
	DEC		A
	LD		(in_pos), A
	LD		HL, (in_buf)
	LD		C, A
	LD		B, 0
	ADD		HL, BC
	XOR		A
	LD		(HL), A					; truncate
	CALL	INP_WAIT_RELEASE
	JR		.redraw
.ignore
	CALL	INP_WAIT_RELEASE
	JR		.poll
.submit
	CALL	INP_WAIT_RELEASE
	OR		A						; CF=0
	RET
.cancel
	CALL	INP_WAIT_RELEASE
	SCF
	RET

; Repaint the status row: prompt + current buffer + an underscore cursor.
INP_DRAW
	CALL	STATUS_HOME
	LD		HL, (in_prompt)
	CALL	TERM.PUTS
	LD		HL, (in_buf)
	CALL	TERM.PUTS
	LD		HL, INP_CURSOR
	JP		TERM.PUTS
INP_CURSOR		DB "_", 0

; Spin until no key is held (ScanKey ZF=1), debouncing one keypress.
INP_WAIT_RELEASE
	CALL	KBD.SCAN
	JR		NZ, INP_WAIT_RELEASE
	RET

; ------------------------------------------------------
; Header bar.
; ------------------------------------------------------
DRAW_HEADER
	LD		D, HEADER_ROW
	LD		E, 0
	LD		H, 1
	LD		L, SCR_W
	LD		B, ATTR_HEADER
	LD		A, ' '
	CALL	TERM.FILL
	LD		D, HEADER_ROW
	LD		E, 1
	CALL	TERM.LOCATE
	LD		HL, DOC_TITLE			; current page title (clicked link / home)
	CALL	TERM.PUTS
	LD		A, 0xFF					; the full-row fill wiped the clock - force a redraw
	LD		(clk_last), A
	RET

; ------------------------------------------------------
; Clock in the header's right corner ("HH:MM:SS", cols 71..78). Called every main-
; loop spin; reads DSS SYSTIME (#21: H=hours, L=minutes, B=seconds, decimal) and
; only repaints when the second changes (clk_last holds the last drawn second; the
; header redraw sets it to 0xFF to force a refresh).
; ------------------------------------------------------
; IDLE_CB entry point. The network kit invokes IDLE_CB from inside its AT/receive
; byte-waits (CHECK_CANCEL_IN_ISA) and restores only AF/BC/DE/HL around the call,
; NOT IX/IY - so we preserve IX/IY here in case SYSTIME/PChars in the clock draw
; clobber a pointer the kit's receive loop relies on. (Stack depth is no longer a
; concern: the runtime stack lives in the WIN2 page at RUN_STACK_TOP, not under
; the lib BSS.)
CLOCK_TICK_CB
	PUSH	IX
	PUSH	IY
	CALL	CLOCK_TICK
	POP		IY
	POP		IX
	RET

CLOCK_TICK
	LD		C, DSS_SYSTIME
	RST		DSS						; H=hours, L=minutes, B=seconds
	LD		A, B
	LD		(now_sec), A			; current second, for the idle-preview timer
	LD		A, H
	LD		(clk_h), A
	LD		A, L
	LD		(clk_m), A
	LD		A, B
	LD		HL, clk_last
	CP		(HL)
	RET		Z						; same second -> nothing to do
	LD		(HL), A					; remember this second
	LD		(clk_s), A
	; build "HH:MM:SS" in CLK_BUF
	LD		HL, CLK_BUF
	LD		A, (clk_h)
	CALL	PUT2D
	LD		(HL), ':'
	INC		HL
	LD		A, (clk_m)
	CALL	PUT2D
	LD		(HL), ':'
	INC		HL
	LD		A, (clk_s)
	CALL	PUT2D
	LD		(HL), 0
	; paint the clock field in header colour (FILL also sets the print colour)
	LD		D, HEADER_ROW
	LD		E, SCR_W - 9			; col 71; leaves col 79 as a margin
	LD		H, 1
	LD		L, 9
	LD		B, ATTR_HEADER
	LD		A, ' '
	CALL	TERM.FILL
	LD		D, HEADER_ROW
	LD		E, SCR_W - 9
	CALL	TERM.LOCATE
	LD		HL, CLK_BUF
	JP		TERM.PUTS

; A = value (0..99) -> two ASCII digits at HL; HL advanced by 2.
PUT2D
	LD		B, '0'
.t
	SUB		10
	JR		C, .units
	INC		B
	JR		.t
.units
	ADD		A, 10 + '0'				; A back to 0..9, then to ASCII
	LD		(HL), B					; tens
	INC		HL
	LD		(HL), A					; units
	INC		HL
	RET

CLK_BUF		DB "00:00:00", 0
clk_last	DB 0xFF
clk_h		DB 0
clk_m		DB 0
clk_s		DB 0
now_sec		DB 0					; current second (set by CLOCK_TICK)
idle_sec	DB 0					; last second the idle timer counted
idle_count	DB 0					; seconds of inactivity (capped at 3)
preview_shown	DB 0				; 1 while a link preview is on the status bar

; ------------------------------------------------------
; Viewport renderer (reads lines straight from the document pages).
; ------------------------------------------------------
RENDER_VIEWPORT
	CALL	ADJUST_VIEW
	LD		BC, (top_index)
	CALL	DOC.SEEK_LINE
	XOR		A
	LD		(r_slot), A
.loop
	LD		A, (r_slot)
	CP		VIEW_ROWS
	RET		Z
	; line index = top_index + r_slot
	LD		HL, (top_index)
	LD		A, (r_slot)
	LD		E, A
	LD		D, 0
	ADD		HL, DE					; HL = line index
	LD		DE, (DOC.doc_lines)
	PUSH	HL
	OR		A
	SBC		HL, DE					; line - lines; CF=1 if line < lines
	POP		HL
	JR		C, .have
	CALL	BLANK_ROW
	JR		.adv
.have
	; selected? compare line index (HL) with sel_index
	LD		DE, (sel_index)
	PUSH	HL
	OR		A
	SBC		HL, DE
	POP		HL
	LD		A, 0
	JR		NZ, .notsel
	INC		A						; A=1 selected
.notsel
	LD		(r_sel_flag), A
	CALL	DOC.NEXT_LINE
	CALL	PARSE_ROW
	LD		A, (r_sel_flag)			; cache the selected row's type for incremental moves
	OR		A
	JR		Z, .nocache
	LD		A, (row_type)
	LD		(sel_type), A
.nocache
	CALL	DRAW_ROW
.adv
	LD		HL, r_slot
	INC		(HL)
	JR		.loop

; Ensure top_index <= sel_index < top_index + VIEW_ROWS.
ADJUST_VIEW
	LD		HL, (sel_index)
	LD		DE, (top_index)
	PUSH	HL
	OR		A
	SBC		HL, DE					; sel - top; CF=1 if sel < top
	POP		HL
	JR		NC, .checkbottom
	LD		(top_index), HL			; top = sel
	RET
.checkbottom
	LD		HL, (top_index)
	LD		DE, VIEW_ROWS
	ADD		HL, DE					; top + VIEW_ROWS
	EX		DE, HL					; DE = top + VIEW_ROWS
	LD		HL, (sel_index)
	OR		A
	SBC		HL, DE					; sel - (top+VIEW_ROWS); CF=1 if in range
	RET		C
	LD		HL, (sel_index)
	LD		DE, VIEW_ROWS - 1
	OR		A
	SBC		HL, DE					; top = sel - VIEW_ROWS + 1
	LD		(top_index), HL
	RET

BLANK_ROW
	LD		A, (r_slot)
	ADD		VIEW_TOP
	LD		D, A
	LD		E, 0
	LD		H, 1
	LD		L, SCR_W
	LD		B, ATTR_NORM
	LD		A, ' '
	JP		TERM.FILL

; Draw the parsed row at slot r_slot, highlighted if r_sel_flag. Menu rows get an
; icon + text at col 2; text-document lines are printed whole from col 1.
DRAW_ROW
	LD		A, (r_sel_flag)
	OR		A
	JR		NZ, .hi
	; not selected: text doc and info/'.' menu rows are plain; links are bright
	LD		A, (DOC_TYPE_CUR)
	CP		'1'
	JR		NZ, .norm				; text document -> normal attr
	LD		A, (row_type)
	CP		'i'
	JR		Z, .norm
	CP		'.'
	JR		Z, .norm
	LD		A, ATTR_LINK
	JR		.haveattr
.hi
	LD		A, ATTR_HILITE
	JR		.haveattr
.norm
	LD		A, ATTR_NORM
.haveattr
	LD		(r_attr), A
	; paint the row background (also sets the colour for following prints)
	LD		A, (r_slot)
	ADD		VIEW_TOP
	LD		D, A
	LD		E, 0
	LD		H, 1
	LD		L, SCR_W
	LD		A, (r_attr)
	LD		B, A
	LD		A, ' '
	CALL	TERM.FILL
	; text document: print the whole line from col 1 (no type byte / no icon)
	LD		A, (DOC_TYPE_CUR)
	CP		'1'
	JR		Z, .menu
	LD		A, (r_slot)
	ADD		VIEW_TOP
	LD		D, A
	LD		E, 1
	CALL	TERM.LOCATE
	CALL	CLIP_DISP
	LD		HL, (p_disp)
	JP		TERM.PUTS
.menu
	; menu row: icon + space + display text at column 2
	LD		A, (r_slot)
	ADD		VIEW_TOP
	LD		D, A
	LD		E, 2
	CALL	TERM.LOCATE
	LD		A, (row_type)
	CALL	GET_ICON
	CALL	TERM.PUTC
	LD		A, ' '
	CALL	TERM.PUTC
	CALL	CLIP_DISP
	LD		HL, (p_disp)
	JP		TERM.PUTS

; Truncate the display string so it fits the row (NUL at the cut point) and
; sanitise it: replace any control byte (< 0x20, e.g. TAB / form-feed / bell) with
; a space, so DSS PChars can't move the cursor / scroll and corrupt the header or
; status row (text documents are printed whole, so they may carry such bytes).
CLIP_DISP
	LD		HL, (p_disp)
	LD		B, SCR_W - 4
.l
	LD		A, (HL)
	OR		A
	RET		Z
	CP		0x20
	JR		NC, .ok
	LD		(HL), ' '				; control char -> space
.ok
	INC		HL
	DJNZ	.l
	LD		(HL), 0
	RET

GET_ICON
	CP		'1'
	JR		Z, .dir
	CP		'0'
	JR		Z, .txt
	CP		'7'
	JR		Z, .search
	CP		'9'
	JR		Z, .bin
	CP		'I'
	JR		Z, .bin
	CP		'g'
	JR		Z, .bin
	CP		'h'
	JR		Z, .link
	CP		'i'
	JR		Z, .info
	LD		A, ' '
	RET
.dir
	LD		A, '/'
	RET
.txt
	LD		A, '='
	RET
.search
	LD		A, '?'
	RET
.bin
	LD		A, '*'
	RET
.link
	LD		A, '@'
	RET
.info
	LD		A, ' '
	RET

; ------------------------------------------------------
; State (WIN1 load image).
; ------------------------------------------------------
sel_index		DW 0
top_index		DW 0
new_sel			DW 0					; pending selection during an incremental move
sel_type		DB 'i'					; gopher type of the selected row (for de-highlight)
r_slot			DB 0
r_attr			DB 0
r_sel_flag		DB 0
row_type		DB 0
p_disp			DW 0
p_sel			DW 0
p_host			DW 0
p_port			DW 0
hist_sp			DB 0
cur_kind		DB 0					; 0=home, 1=network
DOC_TYPE_CUR	DB '1'
net_inited		DB 0
home_fm			DB 0xFF					; open EXE file handle (from (IX-3) at START)
exec_sp			DW 0					; saved SP across Dss.Exec
open_tpl		DW 0					; viewer command template during MAYBE_OPEN
url_ptr			DW 0					; parse pointer for a type-'h' URL
url_full		DW 0					; pointer to the full URL (scheme included)
last_err		DW 0
recv_lo			DW 0					; bytes received this fetch (low 16)
recv_hi			DB 0					; bytes received this fetch (high 8) -> 24-bit
prog_suffix		DW 0					; " bytes"/" KB" pointer during progress draw
NUMBUF			DS 8, 0					; UTIL.UTOA decimal scratch
in_prompt		DW 0					; INPUT_LINE: prompt ASCIIZ
in_buf			DW 0					; INPUT_LINE: destination buffer
in_max			DB 0					; INPUT_LINE: max chars (excl. NUL)
in_pos			DB 0					; INPUT_LINE: chars entered so far
EMPTYSTR		DB 0

; HOST_CUR / PORT_CUR / SEL_CUR now live in WIN2 (console.inc) to spare WIN1 stack.
; Current page title shown in the header (the display text of the link we
; followed; the home page sets a default). Saved/restored across history.
DOC_TITLE		DS TITLE_MAX, 0

; Type-7 search query (entered via INPUT_LINE). WIN1, so TERM.PUTS can echo it.
SEARCH_MAX		EQU 64
SEARCH_BUF		DS SEARCH_MAX, 0

; Binary/media download target (kept separate from the live page's nav so a
; download does not disturb the current document or history).
DL_HOST			DS 64, 0
DL_PORT			DS 8, 0
DL_SEL			DS 200, 0
DL_NAME			DS 16, 0				; derived 8.3 filename
DL_PATH			DS 32, 0				; "DOWNLOAD\<name>" (relative to the EXE dir)
dl_fill			DW 0					; bytes currently buffered in DL_BUF
DL_DIRMK		DB "DOWNLOAD", 0		; mkdir target (relative to the EXE dir)
DL_DIRPFX		DB "DOWNLOAD", 0x5C, 0	; per-file path prefix (backslash separator)
; EXE_DIR / FILE_ABS now live in WIN2 (console.inc) to spare the WIN1 stack.
DEF_DLNAME		DB "INDEX.BIN", 0		; fallback when the selector has no basename
KEY_SKIPASK		DB "skip_ask_for_exec", 0

; One gopher record assembled for Ctrl+D before it is appended to BOOKMARK.GPH.
; Sized for type + title(64) + selector(200) + host(64) + port(8) + TABs + CRLF.
BM_LINE			DS 352, 0

; One decoded gopher row (type + TAB-split fields). MUST be in WIN1 (here in the
; code image), not the WIN2 scratch page: DSS PChars prints the display field
; straight from this buffer, and a WIN2 source prints as garbage.
LINE_BUF		DS 512, 0
LINE_BUF_END	EQU LINE_BUF + 510

; ------------------------------------------------------
; Text.
; ------------------------------------------------------
MSG_TITLE		DB "Gopher browser for Sprinter", 0
MSG_BANNER		DB "GOPHER Browser v.", APP_VERSION, " (", BUILD_DATETIME, ")", 13, 10
				DB "by Dmitry Mikhalchenkov (SprinterTeam)", 13, 10, 0
MSG_RUNEXT		DB "Running external viewer:", 13, 10, 0
MSG_CRLF		DB 13, 10, 0
MSG_STATUS		DB "Up/Dn move  Enter open  Bksp back  ^B bookmarks  ^D add  Esc/F10 quit", 0
MSG_NONET		DB "Wi-Fi not up - run NETUP first (you can still browse the home page)", 0
MSG_CONFIRM_QUIT DB "Quit?  Y = yes,  any other key = no", 0
MSG_FETCHING	DB "Fetching...", 0
MSG_LOADING		DB "Loading ", 0
MSG_LOADED		DB "Loaded ", 0
MSG_INCOMPLETE	DB " - INCOMPLETE (transfer truncated)", 0
SUFFIX_B		DB " bytes", 0
SUFFIX_KB		DB " KB", 0
MSG_UNSUPPORTED	DB "That item type is not supported yet.", 0
MSG_LINKPFX		DB "Web link: ", 0
MSG_OPENURL		DB "Open URL: ", 0
PFX_URL			DB "URL:", 0
SCHEME_GOPHER	DB "gopher://", 0
URL_SCHEME		DS 16, 0
WEBLINK_BUF		DS 80, 0
PREVIEW_BUF		DS 88, 0				; idle link-preview string for the status bar
MSG_SEARCH		DB "Search (Enter=go  Esc=cancel): ", 0
MSG_SAVING		DB "Saving ", 0
MSG_SAVED		DB "Saved ", 0
MSG_TO			DB " to ", 0
MSG_OPEN_ASK	DB "Open in the associated program?  Y = yes,  any other key = no", 0
MSG_BM_TITLE	DB "Bookmarks", 0
MSG_BM_ADDED	DB "Page added to bookmarks.", 0
MSG_BM_NONE		DB "Nothing to bookmark (open a gopher page first).", 0
MSG_BM_FAIL		DB "Could not write the bookmarks file.", 0
MSG_EXEC_FAIL	DB "Could not launch the associated program.", 0
MSG_MEM_ERR		DB "Cannot allocate work page.", 0
ERR_INIT		DB "Network init failed - run NETUP first.", 0
ERR_CONN		DB "Connect failed (check host / port / Wi-Fi).", 0
ERR_SEND		DB "Send failed.", 0
ERR_EMPTY		DB "No data received.", 0
ERR_DISK		DB "Disk write failed (out of space?).", 0
ERR_CANCEL		DB "Cancelled.", 0

; ------------------------------------------------------
; Built-in fallback home page (used only if the INDEX.GPH appended to GOPHER.EXE
; can't be read - e.g. an older DSS that closes the EXE, or a stripped EXE). The
; real home page lives in data/index.gph and is appended by the Makefile.
; ------------------------------------------------------
WELCOME_DOC
	DB "iGopher browser for Sprinter", 13, 10
	DB "iBased on Moon Rabbit / Internet NEXTplorer by nihirash", 13, 10
	DB "i", 13, 10
	DB "i(Appended home page INDEX.GPH not found - using the built-in stub.)", 13, 10
	DB "i", 13, 10
	DB "1Virtual TR-DOS official gopher hole", 9, "/", 9, "vtrd.in", 9, "70", 13, 10
	DB "1Nihirash's gopher hole", 9, "/", 9, "nihirash.net", 9, "70", 13, 10
WELCOME_END
WELCOME_LEN		EQU WELCOME_END - WELCOME_DOC

; Shown by Ctrl+B when BOOKMARK.GPH does not exist yet (or is empty).
BM_EMPTY_DOC
	DB "iNo bookmarks yet.", 13, 10
	DB "i", 13, 10
	DB "iOpen a gopher page, then press Ctrl+D to bookmark it.", 13, 10
	DB "iPress Backspace to go back.", 13, 10
BM_EMPTY_END
BM_EMPTY_LEN	EQU BM_EMPTY_END - BM_EMPTY_DOC

	ENDMODULE

	INCLUDE "term.asm"
	INCLUDE "kbd.asm"
	INCLUDE "doc.asm"
	INCLUDE "net.asm"
	INCLUDE "file.asm"
	INCLUDE "cfg.asm"

; The network kit anchors its BSS chain immediately after the WIN1 image
; (RS_BUFF = post-image RAM). As this app grew, netcfg's 2 KB CFG_BUFF was pushed
; PAST 0x8000 (to ~0x85BA), so it straddled the WIN1/WIN2 page boundary AND
; overlapped STAGE - corrupting the receive buffer and killing the link (the
; "fetching hangs / connection dies" bug). netcfg reads NET.CFG into CFG_BUFF as
; one contiguous block, so it must live wholly within a single physical page and
; not collide with a live buffer. Relocate the whole netcfg BSS into the DL_BUF
; region (4 KB, entirely in the WIN2 page): netcfg's config load runs once inside
; NET.INIT, strictly BEFORE any receive/download touches DL_BUF, so their
; lifetimes are disjoint and aliasing is safe. RS_BUFF + the ESP-TCP BSS stay in
; WIN1 under 0x8000. (The kit exposes this override for exactly this situation.)
	DEFINE NETCFG_BSS_BASE_OVERRIDE		; tell netcfg_lib NOT to self-place its BSS
NETCFG_BSS_BASE		EQU DL_BUF			; ...we place it here (in the WIN2 page) instead
	INCLUDE "netcfg_lib.asm"			; defines _NETCFG (needed by wcommon)
	INCLUDE "wcommon.asm"
	INCLUDE "dss_error.asm"
	INCLUDE "isa.asm"
	INCLUDE "esp_tcp.asm"
	INCLUDE "esplib.asm"				; anchors the lib BSS chain; keep last

; Guard rails against the "network BSS crept past 0x8000" corruption (which silently
; clobbers the WIN2 scratch page and hangs every fetch). RS_BUFF and the ESP-TCP
; BSS are anchored just after the WIN1 image, so they must stay below WIN2 (0x8000);
; netcfg's BSS is deliberately relocated into DL_BUF (WIN2) and must stay within it.
; If the image grows enough to break either, the build fails here instead of at run.
	ASSERT TCP.TCP_BSS_END <= 0x8000		; WIN1 network BSS must not reach the WIN2 page
	ASSERT NETCFG.NETCFG_BSS_END <= DL_BUF + DL_BUF_SIZE	; netcfg BSS must fit inside DL_BUF
	ASSERT NETCFG_BSS_BASE >= 0x8000		; ...and live wholly in the WIN2 page (no boundary split)

; End of the emitted image. The EXE header's LOADER field = IMAGE_END - LOAD_ADDR,
; and the Makefile appends INDEX.GPH starting at file offset 0x200 + that size.
IMAGE_END

	END MAIN.START
